-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pseudoHeaderConstruc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    txEng_shift2pseudoFi_1_dout : IN STD_LOGIC_VECTOR (72 downto 0);
    txEng_shift2pseudoFi_1_empty_n : IN STD_LOGIC;
    txEng_shift2pseudoFi_1_read : OUT STD_LOGIC;
    txEng_tcpMetaFifo_V_dout : IN STD_LOGIC_VECTOR (99 downto 0);
    txEng_tcpMetaFifo_V_empty_n : IN STD_LOGIC;
    txEng_tcpMetaFifo_V_read : OUT STD_LOGIC;
    txEng_tcpTupleFifo_V_dout : IN STD_LOGIC_VECTOR (95 downto 0);
    txEng_tcpTupleFifo_V_empty_n : IN STD_LOGIC;
    txEng_tcpTupleFifo_V_read : OUT STD_LOGIC;
    txEng_tcpPkgBuffer1_s_8_din : OUT STD_LOGIC_VECTOR (72 downto 0);
    txEng_tcpPkgBuffer1_s_8_full_n : IN STD_LOGIC;
    txEng_tcpPkgBuffer1_s_8_write : OUT STD_LOGIC );
end;


architecture behav of pseudoHeaderConstruc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv73_10F00000000B4050402 : STD_LOGIC_VECTOR (72 downto 0) := "1000011110000000000000000000000000000000010110100000001010000010000000010";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv23_40 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001000000";
    constant ap_const_lv23_101 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000100000001";
    constant ap_const_lv22_3F : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000111111";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv9_FF : STD_LOGIC_VECTOR (8 downto 0) := "011111111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv9_101 : STD_LOGIC_VECTOR (8 downto 0) := "100000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv23_100 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000100000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_61 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100001";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv32_C4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000100";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_C9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001001";
    constant ap_const_lv32_CA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001010";
    constant ap_const_lv32_CC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001100";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv256_lc_5 : STD_LOGIC_VECTOR (255 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal state_1_load_load_fu_356_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_nbreadreq_fu_244_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op10_read_state1 : BOOLEAN;
    signal ap_predicate_op15_read_state1 : BOOLEAN;
    signal tmp_nbreadreq_fu_258_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_nbreadreq_fu_266_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op128_read_state1 : BOOLEAN;
    signal ap_predicate_op134_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal state_1_load_reg_1561 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_reg_1565 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op187_write_state2 : BOOLEAN;
    signal tmp_1_reg_1573 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op204_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal state_1 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal header_idx_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal hasBody : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal isSYN : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal header_header_V_6 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000110000000000000000000000000000000000000000000000000000000000000000000000000";
    signal txEng_tcpMetaFifo_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal txEng_tcpTupleFifo_V_blk_n : STD_LOGIC;
    signal txEng_tcpPkgBuffer1_s_8_blk_n : STD_LOGIC;
    signal txEng_shift2pseudoFi_1_blk_n : STD_LOGIC;
    signal reg_351 : STD_LOGIC_VECTOR (72 downto 0);
    signal grp_fu_310_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_1_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_1_reg_1577 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln647_20_fu_483_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_20_reg_1582 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln647_22_fu_493_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_22_reg_1587 : STD_LOGIC_VECTOR (255 downto 0);
    signal sub_ln647_23_fu_569_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_23_reg_1592 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln647_24_fu_579_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_24_reg_1597 : STD_LOGIC_VECTOR (255 downto 0);
    signal and_ln82_1_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_1_reg_1602 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_105_i_reg_1607 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_13_fu_751_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_13_reg_1612 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln647_fu_761_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_reg_1617 : STD_LOGIC_VECTOR (255 downto 0);
    signal sub_ln647_16_fu_885_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_16_reg_1622 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln647_20_fu_895_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_20_reg_1627 : STD_LOGIC_VECTOR (255 downto 0);
    signal and_ln82_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln82_reg_1632 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln887_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln887_reg_1637 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1115_fu_981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_tmp_last_V_phi_fu_297_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_last_V_reg_294 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_last_V_reg_294 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1175_fu_629_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln1115_1_fu_995_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln82_2_fu_605_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln82_fu_921_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln883_fu_1373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_syn_V_fu_1035_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_1421_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_4_fu_1499_p3 : STD_LOGIC_VECTOR (72 downto 0);
    signal tmp_2_5_fu_1550_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal grp_fu_327_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal Lo_assign_s_fu_383_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln76_1_fu_391_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln76_1_fu_395_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln78_1_fu_407_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln76_3_fu_379_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_176_fu_419_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln647_4_fu_427_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln647_3_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln647_17_fu_441_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_19_fu_453_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_177_fu_431_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal sub_ln647_18_fu_447_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_11_fu_459_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_13_fu_475_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_12_fu_467_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal zext_ln647_25_fu_489_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_fu_342_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln647_27_fu_499_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln76_2_fu_375_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_180_fu_509_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln647_4_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln647_2_fu_527_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_22_fu_539_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_181_fu_517_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal sub_ln647_21_fu_533_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_14_fu_545_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_16_fu_561_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_15_fu_553_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal zext_ln647_28_fu_575_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln76_1_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_322_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln76_1_fu_597_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Lo_assign_fu_651_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln76_fu_659_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln76_fu_663_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln78_fu_675_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln76_1_fu_647_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_166_fu_687_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln647_fu_695_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln647_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln647_fu_709_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_12_fu_721_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_167_fu_699_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal sub_ln647_11_fu_715_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_fu_727_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_7_fu_743_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_6_fu_735_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal zext_ln647_fu_757_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal shl_ln_fu_767_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln80_fu_775_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln80_fu_779_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln80_1_fu_793_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln80_1_fu_799_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln647_22_fu_815_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln76_fu_643_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_171_fu_825_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln647_2_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln647_fu_843_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_15_fu_855_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_172_fu_833_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal sub_ln647_14_fu_849_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_8_fu_861_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_10_fu_877_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln647_9_fu_869_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal zext_ln647_23_fu_891_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal icmp_ln76_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln76_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln76_fu_913_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln80_2_fu_809_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_168_fu_785_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_173_fu_935_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_174_fu_945_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln80_fu_955_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln887_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1115_fu_975_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1115_fu_987_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_srcIp_V_fu_1051_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_61_fu_1091_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_dstIp_V_fu_1055_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_length_V_fu_1009_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_33_fu_1115_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln647_5_fu_1131_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_126_i_i_i_fu_1121_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_62_fu_1103_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal agg_result_V_0_1_i_i_fu_1135_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_63_fu_1143_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_srcPort_V_fu_1065_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_64_fu_1155_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_dstPort_V_fu_1075_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln647_6_fu_1209_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_124_2_i_i_fu_1199_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_124_1_i_i_fu_1189_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_124_i_i_i_fu_1179_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_65_fu_1167_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal agg_result_V_0_3_i_i_fu_1213_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_124_3_i_i_1_fu_1267_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_124_2_i_i_1_fu_1257_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_124_1_i_i_1_fu_1247_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_124_i_i_fu_1237_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_66_fu_1225_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal agg_result_V_0_3_i_i_1_fu_1277_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_67_fu_1289_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal select_ln214_fu_1301_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_68_fu_1309_p5 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_fin_V_fu_1043_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_69_fu_1321_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal p_Result_70_fu_1331_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_rst_V_fu_1027_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_71_fu_1341_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_ack_V_fu_1019_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_fu_1367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln761_fu_1361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_126_1_i_i_1_fu_1401_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_126_i_i_fu_1391_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_72_fu_1351_p4 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_s_fu_1411_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln647_26_fu_1449_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_23_fu_1452_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal p_Result_75_fu_1458_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal zext_ln647_29_fu_1467_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_25_fu_1470_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal p_Result_76_fu_1476_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal trunc_ln364_fu_1463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_data_V_fu_1445_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_V_fu_1481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln76_2_fu_1485_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_data_V_11_fu_1492_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln647_21_fu_1507_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_19_fu_1510_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal zext_ln647_24_fu_1521_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln647_21_fu_1524_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal p_Result_74_fu_1530_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal p_Result_73_fu_1516_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal trunc_ln82_fu_1535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln82_1_fu_1539_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sendWord_data_V_fu_1543_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_124 : BOOLEAN;
    signal ap_condition_67 : BOOLEAN;
    signal ap_condition_267 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_tmp_last_V_reg_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_124)) then
                if (((or_ln887_fu_969_p2 = ap_const_lv1_1) and (state_1_load_load_fu_356_p1 = ap_const_lv3_1))) then 
                    ap_phi_reg_pp0_iter1_tmp_last_V_reg_294 <= xor_ln1115_fu_981_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_tmp_last_V_reg_294 <= ap_phi_reg_pp0_iter0_tmp_last_V_reg_294;
                end if;
            end if; 
        end if;
    end process;

    header_idx_5_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_124)) then
                if ((ap_const_boolean_1 = ap_condition_67)) then 
                    header_idx_5 <= ap_const_lv16_0;
                elsif ((state_1_load_load_fu_356_p1 = ap_const_lv3_1)) then 
                    header_idx_5 <= select_ln82_fu_921_p3;
                elsif (((grp_nbreadreq_fu_244_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_2))) then 
                    header_idx_5 <= select_ln82_2_fu_605_p3;
                end if;
            end if; 
        end if;
    end process;

    state_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_3_nbreadreq_fu_266_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_258_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                state_1 <= ap_const_lv3_1;
            elsif (((or_ln887_fu_969_p2 = ap_const_lv1_1) and (state_1_load_load_fu_356_p1 = ap_const_lv3_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                state_1 <= select_ln1115_1_fu_995_p3;
            elsif (((grp_nbreadreq_fu_244_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                state_1 <= select_ln1175_fu_629_p3;
            elsif ((((grp_fu_310_p3 = ap_const_lv1_1) and (grp_nbreadreq_fu_244_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_3) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((state_1_load_load_fu_356_p1 = ap_const_lv3_4) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                state_1 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nbreadreq_fu_244_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln82_1_reg_1602 <= and_ln82_1_fu_591_p2;
                icmp_ln76_1_reg_1577 <= icmp_ln76_1_fu_401_p2;
                lshr_ln647_22_reg_1587 <= lshr_ln647_22_fu_493_p2;
                lshr_ln647_24_reg_1597 <= lshr_ln647_24_fu_579_p2;
                    sub_ln647_20_reg_1582(8 downto 1) <= sub_ln647_20_fu_483_p2(8 downto 1);
                    sub_ln647_23_reg_1592(8 downto 1) <= sub_ln647_23_fu_569_p2(8 downto 1);
                tmp_105_i_reg_1607 <= txEng_shift2pseudoFi_1_dout(72 downto 64);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_1_load_load_fu_356_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln82_reg_1632 <= and_ln82_fu_907_p2;
                lshr_ln647_20_reg_1627 <= lshr_ln647_20_fu_895_p2;
                lshr_ln647_reg_1617 <= lshr_ln647_fu_761_p2;
                or_ln887_reg_1637 <= or_ln887_fu_969_p2;
                    sub_ln647_13_reg_1612(8 downto 1) <= sub_ln647_13_fu_751_p2(8 downto 1);
                    sub_ln647_16_reg_1622(8 downto 1) <= sub_ln647_16_fu_885_p2(8 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_3_nbreadreq_fu_266_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_258_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                hasBody <= and_ln883_fu_1373_p2;
                header_header_V_6 <= p_Result_s_fu_1421_p5;
                isSYN <= txEng_tcpMetaFifo_V_dout(98 downto 98);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op15_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_351 <= txEng_shift2pseudoFi_1_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                state_1_load_reg_1561 <= state_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_1 = ap_const_lv3_2) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_1_reg_1573 <= grp_nbreadreq_fu_244_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_1 = ap_const_lv3_3) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_2_reg_1565 <= grp_nbreadreq_fu_244_p3;
            end if;
        end if;
    end process;
    sub_ln647_20_reg_1582(0) <= '0';
    sub_ln647_23_reg_1592(0) <= '0';
    sub_ln647_13_reg_1612(0) <= '0';
    sub_ln647_16_reg_1622(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Lo_assign_fu_651_p3 <= (header_idx_5 & ap_const_lv6_0);
    Lo_assign_s_fu_383_p3 <= (header_idx_5 & ap_const_lv6_0);
    add_ln647_2_fu_527_p2 <= std_logic_vector(unsigned(tmp_180_fu_509_p3) + unsigned(ap_const_lv9_101));
    add_ln647_fu_843_p2 <= std_logic_vector(unsigned(tmp_171_fu_825_p3) + unsigned(ap_const_lv9_101));
    add_ln76_1_fu_395_p2 <= std_logic_vector(unsigned(zext_ln76_1_fu_391_p1) + unsigned(ap_const_lv23_40));
    add_ln76_fu_663_p2 <= std_logic_vector(unsigned(zext_ln76_fu_659_p1) + unsigned(ap_const_lv23_40));
    agg_result_V_0_1_i_i_fu_1135_p3 <= (trunc_ln647_5_fu_1131_p1 & p_Result_126_i_i_i_fu_1121_p4);
    agg_result_V_0_3_i_i_1_fu_1277_p5 <= (((p_Result_124_3_i_i_1_fu_1267_p4 & p_Result_124_2_i_i_1_fu_1257_p4) & p_Result_124_1_i_i_1_fu_1247_p4) & p_Result_124_i_i_fu_1237_p4);
    agg_result_V_0_3_i_i_fu_1213_p5 <= (((trunc_ln647_6_fu_1209_p1 & p_Result_124_2_i_i_fu_1199_p4) & p_Result_124_1_i_i_fu_1189_p4) & p_Result_124_i_i_i_fu_1179_p4);
    and_ln82_1_fu_591_p2 <= (xor_ln76_1_fu_585_p2 and grp_fu_336_p2);
    and_ln82_fu_907_p2 <= (xor_ln76_fu_901_p2 and grp_fu_336_p2);
    and_ln883_fu_1373_p2 <= (xor_ln761_fu_1361_p2 and icmp_ln883_fu_1367_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, txEng_shift2pseudoFi_1_empty_n, ap_predicate_op10_read_state1, ap_predicate_op15_read_state1, txEng_tcpMetaFifo_V_empty_n, ap_predicate_op128_read_state1, txEng_tcpTupleFifo_V_empty_n, ap_predicate_op134_read_state1, txEng_tcpPkgBuffer1_s_8_full_n, state_1_load_reg_1561, ap_predicate_op187_write_state2, ap_predicate_op204_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((txEng_tcpTupleFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op134_read_state1 = ap_const_boolean_1)) or ((txEng_tcpMetaFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op15_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_1_load_reg_1561 = ap_const_lv3_4) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((state_1_load_reg_1561 = ap_const_lv3_1) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op204_write_state2 = ap_const_boolean_1)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op187_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, txEng_shift2pseudoFi_1_empty_n, ap_predicate_op10_read_state1, ap_predicate_op15_read_state1, txEng_tcpMetaFifo_V_empty_n, ap_predicate_op128_read_state1, txEng_tcpTupleFifo_V_empty_n, ap_predicate_op134_read_state1, txEng_tcpPkgBuffer1_s_8_full_n, state_1_load_reg_1561, ap_predicate_op187_write_state2, ap_predicate_op204_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((txEng_tcpTupleFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op134_read_state1 = ap_const_boolean_1)) or ((txEng_tcpMetaFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op15_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_1_load_reg_1561 = ap_const_lv3_4) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((state_1_load_reg_1561 = ap_const_lv3_1) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op204_write_state2 = ap_const_boolean_1)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op187_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, txEng_shift2pseudoFi_1_empty_n, ap_predicate_op10_read_state1, ap_predicate_op15_read_state1, txEng_tcpMetaFifo_V_empty_n, ap_predicate_op128_read_state1, txEng_tcpTupleFifo_V_empty_n, ap_predicate_op134_read_state1, txEng_tcpPkgBuffer1_s_8_full_n, state_1_load_reg_1561, ap_predicate_op187_write_state2, ap_predicate_op204_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((txEng_tcpTupleFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op134_read_state1 = ap_const_boolean_1)) or ((txEng_tcpMetaFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op15_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((state_1_load_reg_1561 = ap_const_lv3_4) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((state_1_load_reg_1561 = ap_const_lv3_1) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op204_write_state2 = ap_const_boolean_1)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op187_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, txEng_shift2pseudoFi_1_empty_n, ap_predicate_op10_read_state1, ap_predicate_op15_read_state1, txEng_tcpMetaFifo_V_empty_n, ap_predicate_op128_read_state1, txEng_tcpTupleFifo_V_empty_n, ap_predicate_op134_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((txEng_tcpTupleFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op134_read_state1 = ap_const_boolean_1)) or ((txEng_tcpMetaFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op128_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op15_read_state1 = ap_const_boolean_1)) or ((txEng_shift2pseudoFi_1_empty_n = ap_const_logic_0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(txEng_tcpPkgBuffer1_s_8_full_n, state_1_load_reg_1561, ap_predicate_op187_write_state2, ap_predicate_op204_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((state_1_load_reg_1561 = ap_const_lv3_4) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((state_1_load_reg_1561 = ap_const_lv3_1) and (txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op204_write_state2 = ap_const_boolean_1)) or ((txEng_tcpPkgBuffer1_s_8_full_n = ap_const_logic_0) and (ap_predicate_op187_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_124_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_124 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_267_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_267 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_67_assign_proc : process(tmp_nbreadreq_fu_258_p3, tmp_3_nbreadreq_fu_266_p3, state_1)
    begin
                ap_condition_67 <= ((tmp_3_nbreadreq_fu_266_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_258_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_tmp_last_V_phi_fu_297_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_1_load_reg_1561, ap_block_pp0_stage0, or_ln887_reg_1637, ap_phi_reg_pp0_iter1_tmp_last_V_reg_294)
    begin
        if (((state_1_load_reg_1561 = ap_const_lv3_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln887_reg_1637 = ap_const_lv1_0))) then 
            ap_phi_mux_tmp_last_V_phi_fu_297_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_tmp_last_V_phi_fu_297_p4 <= ap_phi_reg_pp0_iter1_tmp_last_V_reg_294;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_tmp_last_V_reg_294 <= "X";

    ap_predicate_op10_read_state1_assign_proc : process(grp_nbreadreq_fu_244_p3, state_1)
    begin
                ap_predicate_op10_read_state1 <= ((grp_nbreadreq_fu_244_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_3));
    end process;


    ap_predicate_op128_read_state1_assign_proc : process(tmp_nbreadreq_fu_258_p3, tmp_3_nbreadreq_fu_266_p3, state_1)
    begin
                ap_predicate_op128_read_state1 <= ((tmp_3_nbreadreq_fu_266_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_258_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_0));
    end process;


    ap_predicate_op134_read_state1_assign_proc : process(tmp_nbreadreq_fu_258_p3, tmp_3_nbreadreq_fu_266_p3, state_1)
    begin
                ap_predicate_op134_read_state1 <= ((tmp_3_nbreadreq_fu_266_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_258_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_0));
    end process;


    ap_predicate_op15_read_state1_assign_proc : process(grp_nbreadreq_fu_244_p3, state_1)
    begin
                ap_predicate_op15_read_state1 <= ((grp_nbreadreq_fu_244_p3 = ap_const_lv1_1) and (state_1 = ap_const_lv3_2));
    end process;


    ap_predicate_op187_write_state2_assign_proc : process(state_1_load_reg_1561, tmp_2_reg_1565)
    begin
                ap_predicate_op187_write_state2 <= ((tmp_2_reg_1565 = ap_const_lv1_1) and (state_1_load_reg_1561 = ap_const_lv3_3));
    end process;


    ap_predicate_op204_write_state2_assign_proc : process(state_1_load_reg_1561, tmp_1_reg_1573)
    begin
                ap_predicate_op204_write_state2 <= ((state_1_load_reg_1561 = ap_const_lv3_2) and (tmp_1_reg_1573 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_310_p3 <= txEng_shift2pseudoFi_1_dout(72 downto 72);
    grp_fu_322_p2 <= std_logic_vector(unsigned(header_idx_5) + unsigned(ap_const_lv16_1));
    grp_fu_327_p4 <= header_idx_5(15 downto 2);
    grp_fu_336_p2 <= "1" when (grp_fu_327_p4 = ap_const_lv14_0) else "0";
    grp_fu_342_p4 <= header_idx_5(15 downto 2);
    grp_nbreadreq_fu_244_p3 <= (0=>(txEng_shift2pseudoFi_1_empty_n), others=>'-');
    icmp_ln647_2_fu_819_p2 <= "0" when (zext_ln647_22_fu_815_p1 = ap_const_lv24_0) else "1";
    icmp_ln647_3_fu_413_p2 <= "1" when (unsigned(Lo_assign_s_fu_383_p3) > unsigned(or_ln78_1_fu_407_p2)) else "0";
    icmp_ln647_4_fu_503_p2 <= "0" when (zext_ln647_27_fu_499_p1 = ap_const_lv24_0) else "1";
    icmp_ln647_fu_681_p2 <= "1" when (unsigned(Lo_assign_fu_651_p3) > unsigned(or_ln78_fu_675_p2)) else "0";
    icmp_ln76_1_fu_401_p2 <= "1" when (unsigned(add_ln76_1_fu_395_p2) < unsigned(ap_const_lv23_101)) else "0";
    icmp_ln76_fu_669_p2 <= "1" when (unsigned(add_ln76_fu_663_p2) < unsigned(ap_const_lv23_101)) else "0";
    icmp_ln883_fu_1367_p2 <= "0" when (tmp_length_V_fu_1009_p4 = ap_const_lv16_0) else "1";
    icmp_ln887_fu_963_p2 <= "1" when (select_ln80_fu_955_p3 = ap_const_lv5_0) else "0";
    lshr_ln647_19_fu_1510_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv256_lc_5),to_integer(unsigned('0' & zext_ln647_21_fu_1507_p1(31-1 downto 0)))));
    lshr_ln647_20_fu_895_p2 <= std_logic_vector(shift_right(unsigned(select_ln647_9_fu_869_p3),to_integer(unsigned('0' & zext_ln647_23_fu_891_p1(31-1 downto 0)))));
    lshr_ln647_21_fu_1524_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv256_lc_5),to_integer(unsigned('0' & zext_ln647_24_fu_1521_p1(31-1 downto 0)))));
    lshr_ln647_22_fu_493_p2 <= std_logic_vector(shift_right(unsigned(select_ln647_12_fu_467_p3),to_integer(unsigned('0' & zext_ln647_25_fu_489_p1(31-1 downto 0)))));
    lshr_ln647_23_fu_1452_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv256_lc_5),to_integer(unsigned('0' & zext_ln647_26_fu_1449_p1(31-1 downto 0)))));
    lshr_ln647_24_fu_579_p2 <= std_logic_vector(shift_right(unsigned(select_ln647_15_fu_553_p3),to_integer(unsigned('0' & zext_ln647_28_fu_575_p1(31-1 downto 0)))));
    lshr_ln647_25_fu_1470_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv256_lc_5),to_integer(unsigned('0' & zext_ln647_29_fu_1467_p1(31-1 downto 0)))));
    lshr_ln647_fu_761_p2 <= std_logic_vector(shift_right(unsigned(select_ln647_6_fu_735_p3),to_integer(unsigned('0' & zext_ln647_fu_757_p1(31-1 downto 0)))));
    or_ln1115_fu_975_p2 <= (isSYN or hasBody);
    or_ln78_1_fu_407_p2 <= (ap_const_lv22_3F or Lo_assign_s_fu_383_p3);
    or_ln78_fu_675_p2 <= (ap_const_lv22_3F or Lo_assign_fu_651_p3);
    or_ln887_fu_969_p2 <= (xor_ln76_fu_901_p2 or icmp_ln887_fu_963_p2);
    p_Result_124_1_i_i_1_fu_1247_p4 <= txEng_tcpMetaFifo_V_dout(55 downto 48);
    p_Result_124_1_i_i_fu_1189_p4 <= txEng_tcpMetaFifo_V_dout(23 downto 16);
    p_Result_124_2_i_i_1_fu_1257_p4 <= txEng_tcpMetaFifo_V_dout(47 downto 40);
    p_Result_124_2_i_i_fu_1199_p4 <= txEng_tcpMetaFifo_V_dout(15 downto 8);
    p_Result_124_3_i_i_1_fu_1267_p4 <= txEng_tcpMetaFifo_V_dout(39 downto 32);
    p_Result_124_i_i_fu_1237_p4 <= txEng_tcpMetaFifo_V_dout(63 downto 56);
    p_Result_124_i_i_i_fu_1179_p4 <= txEng_tcpMetaFifo_V_dout(31 downto 24);
    p_Result_126_1_i_i_1_fu_1401_p4 <= txEng_tcpMetaFifo_V_dout(71 downto 64);
    p_Result_126_i_i_fu_1391_p4 <= txEng_tcpMetaFifo_V_dout(79 downto 72);
    p_Result_126_i_i_i_fu_1121_p4 <= p_Val2_33_fu_1115_p2(15 downto 8);
    p_Result_61_fu_1091_p5 <= (header_header_V_6(255 downto 32) & tmp_srcIp_V_fu_1051_p1);
    p_Result_62_fu_1103_p5 <= (p_Result_61_fu_1091_p5(255 downto 64) & tmp_dstIp_V_fu_1055_p4 & p_Result_61_fu_1091_p5(31 downto 0));
    p_Result_63_fu_1143_p5 <= (p_Result_62_fu_1103_p5(255 downto 96) & agg_result_V_0_1_i_i_fu_1135_p3 & p_Result_62_fu_1103_p5(79 downto 0));
    p_Result_64_fu_1155_p5 <= (p_Result_63_fu_1143_p5(255 downto 112) & tmp_srcPort_V_fu_1065_p4 & p_Result_63_fu_1143_p5(95 downto 0));
    p_Result_65_fu_1167_p5 <= (p_Result_64_fu_1155_p5(255 downto 128) & tmp_dstPort_V_fu_1075_p4 & p_Result_64_fu_1155_p5(111 downto 0));
    p_Result_66_fu_1225_p5 <= (p_Result_65_fu_1167_p5(255 downto 160) & agg_result_V_0_3_i_i_fu_1213_p5 & p_Result_65_fu_1167_p5(127 downto 0));
    p_Result_67_fu_1289_p5 <= (p_Result_66_fu_1225_p5(255 downto 192) & agg_result_V_0_3_i_i_1_fu_1277_p5 & p_Result_66_fu_1225_p5(159 downto 0));
    p_Result_68_fu_1309_p5 <= (p_Result_67_fu_1289_p5(255 downto 200) & select_ln214_fu_1301_p3 & p_Result_67_fu_1289_p5(195 downto 0));
    
    p_Result_69_fu_1321_p4_proc : process(p_Result_68_fu_1309_p5, tmp_fin_V_fu_1043_p3)
    begin
        p_Result_69_fu_1321_p4 <= p_Result_68_fu_1309_p5;
        p_Result_69_fu_1321_p4(200) <= tmp_fin_V_fu_1043_p3(0);
    end process;

    
    p_Result_70_fu_1331_p4_proc : process(p_Result_69_fu_1321_p4, tmp_syn_V_fu_1035_p3)
    begin
        p_Result_70_fu_1331_p4 <= p_Result_69_fu_1321_p4;
        p_Result_70_fu_1331_p4(201) <= tmp_syn_V_fu_1035_p3(0);
    end process;

    
    p_Result_71_fu_1341_p4_proc : process(p_Result_70_fu_1331_p4, tmp_rst_V_fu_1027_p3)
    begin
        p_Result_71_fu_1341_p4 <= p_Result_70_fu_1331_p4;
        p_Result_71_fu_1341_p4(202) <= tmp_rst_V_fu_1027_p3(0);
    end process;

    
    p_Result_72_fu_1351_p4_proc : process(p_Result_71_fu_1341_p4, tmp_ack_V_fu_1019_p3)
    begin
        p_Result_72_fu_1351_p4 <= p_Result_71_fu_1341_p4;
        p_Result_72_fu_1351_p4(204) <= tmp_ack_V_fu_1019_p3(0);
    end process;

    p_Result_73_fu_1516_p2 <= (lshr_ln647_reg_1617 and lshr_ln647_19_fu_1510_p2);
    p_Result_74_fu_1530_p2 <= (lshr_ln647_21_fu_1524_p2 and lshr_ln647_20_reg_1627);
    p_Result_75_fu_1458_p2 <= (lshr_ln647_23_fu_1452_p2 and lshr_ln647_22_reg_1587);
    p_Result_76_fu_1476_p2 <= (lshr_ln647_25_fu_1470_p2 and lshr_ln647_24_reg_1597);
    p_Result_s_fu_1421_p5 <= (p_Result_72_fu_1351_p4(255 downto 240) & tmp_s_fu_1411_p4 & p_Result_72_fu_1351_p4(207 downto 0));
    p_Val2_33_fu_1115_p2 <= std_logic_vector(unsigned(ap_const_lv16_14) + unsigned(tmp_length_V_fu_1009_p4));
    select_ln1115_1_fu_995_p3 <= 
        select_ln1115_fu_987_p3 when (or_ln1115_fu_975_p2(0) = '1') else 
        ap_const_lv3_0;
    select_ln1115_fu_987_p3 <= 
        ap_const_lv3_3 when (hasBody(0) = '1') else 
        ap_const_lv3_4;
    select_ln1175_fu_629_p3 <= 
        ap_const_lv3_0 when (grp_fu_310_p3(0) = '1') else 
        ap_const_lv3_3;
    select_ln214_fu_1301_p3 <= 
        ap_const_lv4_6 when (tmp_syn_V_fu_1035_p3(0) = '1') else 
        ap_const_lv4_5;
    select_ln647_10_fu_877_p3 <= 
        sub_ln647_14_fu_849_p2 when (icmp_ln647_2_fu_819_p2(0) = '1') else 
        tmp_171_fu_825_p3;
    select_ln647_11_fu_459_p3 <= 
        sub_ln647_17_fu_441_p2 when (icmp_ln647_3_fu_413_p2(0) = '1') else 
        sub_ln647_19_fu_453_p2;
    select_ln647_12_fu_467_p3 <= 
        tmp_177_fu_431_p4 when (icmp_ln647_3_fu_413_p2(0) = '1') else 
        header_header_V_6;
    select_ln647_13_fu_475_p3 <= 
        sub_ln647_18_fu_447_p2 when (icmp_ln647_3_fu_413_p2(0) = '1') else 
        tmp_176_fu_419_p3;
    select_ln647_14_fu_545_p3 <= 
        add_ln647_2_fu_527_p2 when (icmp_ln647_4_fu_503_p2(0) = '1') else 
        sub_ln647_22_fu_539_p2;
    select_ln647_15_fu_553_p3 <= 
        tmp_181_fu_517_p4 when (icmp_ln647_4_fu_503_p2(0) = '1') else 
        header_header_V_6;
    select_ln647_16_fu_561_p3 <= 
        sub_ln647_21_fu_533_p2 when (icmp_ln647_4_fu_503_p2(0) = '1') else 
        tmp_180_fu_509_p3;
    select_ln647_6_fu_735_p3 <= 
        tmp_167_fu_699_p4 when (icmp_ln647_fu_681_p2(0) = '1') else 
        header_header_V_6;
    select_ln647_7_fu_743_p3 <= 
        sub_ln647_11_fu_715_p2 when (icmp_ln647_fu_681_p2(0) = '1') else 
        tmp_166_fu_687_p3;
    select_ln647_8_fu_861_p3 <= 
        add_ln647_fu_843_p2 when (icmp_ln647_2_fu_819_p2(0) = '1') else 
        sub_ln647_15_fu_855_p2;
    select_ln647_9_fu_869_p3 <= 
        tmp_172_fu_833_p4 when (icmp_ln647_2_fu_819_p2(0) = '1') else 
        header_header_V_6;
    select_ln647_fu_727_p3 <= 
        sub_ln647_fu_709_p2 when (icmp_ln647_fu_681_p2(0) = '1') else 
        sub_ln647_12_fu_721_p2;
    select_ln76_1_fu_597_p3 <= 
        grp_fu_322_p2 when (icmp_ln76_1_fu_401_p2(0) = '1') else 
        header_idx_5;
    select_ln76_2_fu_1485_p3 <= 
        trunc_ln364_fu_1463_p1 when (icmp_ln76_1_reg_1577(0) = '1') else 
        tmp_data_V_fu_1445_p1;
    select_ln76_fu_913_p3 <= 
        grp_fu_322_p2 when (icmp_ln76_fu_669_p2(0) = '1') else 
        header_idx_5;
    select_ln80_fu_955_p3 <= 
        tmp_173_fu_935_p4 when (tmp_168_fu_785_p3(0) = '1') else 
        tmp_174_fu_945_p4;
    select_ln82_2_fu_605_p3 <= 
        grp_fu_322_p2 when (and_ln82_1_fu_591_p2(0) = '1') else 
        select_ln76_1_fu_597_p3;
    select_ln82_fu_921_p3 <= 
        grp_fu_322_p2 when (and_ln82_fu_907_p2(0) = '1') else 
        select_ln76_fu_913_p3;
    sendWord_data_V_fu_1543_p3 <= 
        trunc_ln82_fu_1535_p1 when (and_ln82_reg_1632(0) = '1') else 
        trunc_ln82_1_fu_1539_p1;
    shl_ln_fu_767_p3 <= (grp_fu_322_p2 & ap_const_lv6_0);
    state_1_load_load_fu_356_p1 <= state_1;
    sub_ln647_11_fu_715_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(tmp_166_fu_687_p3));
    sub_ln647_12_fu_721_p2 <= std_logic_vector(unsigned(trunc_ln647_fu_695_p1) - unsigned(tmp_166_fu_687_p3));
    sub_ln647_13_fu_751_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(select_ln647_fu_727_p3));
    sub_ln647_14_fu_849_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(tmp_171_fu_825_p3));
    sub_ln647_15_fu_855_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(tmp_171_fu_825_p3));
    sub_ln647_16_fu_885_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(select_ln647_8_fu_861_p3));
    sub_ln647_17_fu_441_p2 <= std_logic_vector(unsigned(tmp_176_fu_419_p3) - unsigned(trunc_ln647_4_fu_427_p1));
    sub_ln647_18_fu_447_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(tmp_176_fu_419_p3));
    sub_ln647_19_fu_453_p2 <= std_logic_vector(unsigned(trunc_ln647_4_fu_427_p1) - unsigned(tmp_176_fu_419_p3));
    sub_ln647_20_fu_483_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(select_ln647_11_fu_459_p3));
    sub_ln647_21_fu_533_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(tmp_180_fu_509_p3));
    sub_ln647_22_fu_539_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(tmp_180_fu_509_p3));
    sub_ln647_23_fu_569_p2 <= std_logic_vector(unsigned(ap_const_lv9_FF) - unsigned(select_ln647_14_fu_545_p3));
    sub_ln647_fu_709_p2 <= std_logic_vector(unsigned(tmp_166_fu_687_p3) - unsigned(trunc_ln647_fu_695_p1));
    sub_ln80_1_fu_793_p2 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(sub_ln80_fu_779_p2));
    sub_ln80_2_fu_809_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(trunc_ln80_1_fu_799_p4));
    sub_ln80_fu_779_p2 <= std_logic_vector(unsigned(ap_const_lv23_100) - unsigned(zext_ln80_fu_775_p1));
    tmp_166_fu_687_p3 <= (trunc_ln76_1_fu_647_p1 & ap_const_lv6_0);
    
    tmp_167_fu_699_p4_proc : process(header_header_V_6)
    variable vlo_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_167_fu_699_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(8 - 1 downto 0) := ap_const_lv32_FF(8 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(8 - 1 downto 0) := ap_const_lv32_0(8 - 1 downto 0);
        v0_cpy := header_header_V_6;
        if (vlo_cpy(8 - 1 downto 0) > vhi_cpy(8 - 1 downto 0)) then
            vhi_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_0(8-1 downto 0)));
            vlo_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_FF(8-1 downto 0)));
            for tmp_167_fu_699_p4_i in 0 to 256-1 loop
                v0_cpy(tmp_167_fu_699_p4_i) := header_header_V_6(256-1-tmp_167_fu_699_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(8-1 downto 0)))));

        section := (others=>'0');
        section(8-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(8-1 downto 0)) - unsigned(vlo_cpy(8-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(256-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_167_fu_699_p4 <= resvalue(256-1 downto 0);
    end process;

    tmp_168_fu_785_p3 <= sub_ln80_fu_779_p2(22 downto 22);
    tmp_171_fu_825_p3 <= (trunc_ln76_fu_643_p1 & ap_const_lv6_0);
    
    tmp_172_fu_833_p4_proc : process(header_header_V_6)
    variable vlo_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_172_fu_833_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(8 - 1 downto 0) := ap_const_lv32_FF(8 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(8 - 1 downto 0) := ap_const_lv32_0(8 - 1 downto 0);
        v0_cpy := header_header_V_6;
        if (vlo_cpy(8 - 1 downto 0) > vhi_cpy(8 - 1 downto 0)) then
            vhi_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_0(8-1 downto 0)));
            vlo_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_FF(8-1 downto 0)));
            for tmp_172_fu_833_p4_i in 0 to 256-1 loop
                v0_cpy(tmp_172_fu_833_p4_i) := header_header_V_6(256-1-tmp_172_fu_833_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(8-1 downto 0)))));

        section := (others=>'0');
        section(8-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(8-1 downto 0)) - unsigned(vlo_cpy(8-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(256-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_172_fu_833_p4 <= resvalue(256-1 downto 0);
    end process;

    tmp_173_fu_935_p4 <= sub_ln80_2_fu_809_p2(7 downto 3);
    tmp_174_fu_945_p4 <= sub_ln80_fu_779_p2(10 downto 6);
    tmp_176_fu_419_p3 <= (trunc_ln76_3_fu_379_p1 & ap_const_lv6_0);
    
    tmp_177_fu_431_p4_proc : process(header_header_V_6)
    variable vlo_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_177_fu_431_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(8 - 1 downto 0) := ap_const_lv32_FF(8 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(8 - 1 downto 0) := ap_const_lv32_0(8 - 1 downto 0);
        v0_cpy := header_header_V_6;
        if (vlo_cpy(8 - 1 downto 0) > vhi_cpy(8 - 1 downto 0)) then
            vhi_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_0(8-1 downto 0)));
            vlo_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_FF(8-1 downto 0)));
            for tmp_177_fu_431_p4_i in 0 to 256-1 loop
                v0_cpy(tmp_177_fu_431_p4_i) := header_header_V_6(256-1-tmp_177_fu_431_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(8-1 downto 0)))));

        section := (others=>'0');
        section(8-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(8-1 downto 0)) - unsigned(vlo_cpy(8-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(256-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_177_fu_431_p4 <= resvalue(256-1 downto 0);
    end process;

    tmp_180_fu_509_p3 <= (trunc_ln76_2_fu_375_p1 & ap_const_lv6_0);
    
    tmp_181_fu_517_p4_proc : process(header_header_V_6)
    variable vlo_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(256+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_181_fu_517_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(256 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(8 - 1 downto 0) := ap_const_lv32_FF(8 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(8 - 1 downto 0) := ap_const_lv32_0(8 - 1 downto 0);
        v0_cpy := header_header_V_6;
        if (vlo_cpy(8 - 1 downto 0) > vhi_cpy(8 - 1 downto 0)) then
            vhi_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_0(8-1 downto 0)));
            vlo_cpy(8-1 downto 0) := std_logic_vector(256-1-unsigned(ap_const_lv32_FF(8-1 downto 0)));
            for tmp_181_fu_517_p4_i in 0 to 256-1 loop
                v0_cpy(tmp_181_fu_517_p4_i) := header_header_V_6(256-1-tmp_181_fu_517_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(8-1 downto 0)))));

        section := (others=>'0');
        section(8-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(8-1 downto 0)) - unsigned(vlo_cpy(8-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(256-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_181_fu_517_p4 <= resvalue(256-1 downto 0);
    end process;

    tmp_2_5_fu_1550_p4 <= ((ap_phi_mux_tmp_last_V_phi_fu_297_p4 & ap_const_lv8_FF) & sendWord_data_V_fu_1543_p3);
    tmp_3_nbreadreq_fu_266_p3 <= (0=>(txEng_tcpTupleFifo_V_empty_n), others=>'-');
    tmp_4_fu_1499_p3 <= (tmp_105_i_reg_1607 & tmp_data_V_11_fu_1492_p3);
    tmp_V_fu_1481_p1 <= p_Result_76_fu_1476_p2(64 - 1 downto 0);
    tmp_ack_V_fu_1019_p3 <= txEng_tcpMetaFifo_V_dout(96 downto 96);
    tmp_data_V_11_fu_1492_p3 <= 
        tmp_V_fu_1481_p1 when (and_ln82_1_reg_1602(0) = '1') else 
        select_ln76_2_fu_1485_p3;
    tmp_data_V_fu_1445_p1 <= reg_351(64 - 1 downto 0);
    tmp_dstIp_V_fu_1055_p4 <= txEng_tcpTupleFifo_V_dout(63 downto 32);
    tmp_dstPort_V_fu_1075_p4 <= txEng_tcpTupleFifo_V_dout(95 downto 80);
    tmp_fin_V_fu_1043_p3 <= txEng_tcpMetaFifo_V_dout(99 downto 99);
    tmp_length_V_fu_1009_p4 <= txEng_tcpMetaFifo_V_dout(95 downto 80);
    tmp_nbreadreq_fu_258_p3 <= (0=>(txEng_tcpMetaFifo_V_empty_n), others=>'-');
    tmp_rst_V_fu_1027_p3 <= txEng_tcpMetaFifo_V_dout(97 downto 97);
    tmp_s_fu_1411_p4 <= ((ap_const_lv16_0 & p_Result_126_1_i_i_1_fu_1401_p4) & p_Result_126_i_i_fu_1391_p4);
    tmp_srcIp_V_fu_1051_p1 <= txEng_tcpTupleFifo_V_dout(32 - 1 downto 0);
    tmp_srcPort_V_fu_1065_p4 <= txEng_tcpTupleFifo_V_dout(79 downto 64);
    tmp_syn_V_fu_1035_p3 <= txEng_tcpMetaFifo_V_dout(98 downto 98);
    trunc_ln364_fu_1463_p1 <= p_Result_75_fu_1458_p2(64 - 1 downto 0);
    trunc_ln647_4_fu_427_p1 <= or_ln78_1_fu_407_p2(9 - 1 downto 0);
    trunc_ln647_5_fu_1131_p1 <= p_Val2_33_fu_1115_p2(8 - 1 downto 0);
    trunc_ln647_6_fu_1209_p1 <= txEng_tcpMetaFifo_V_dout(8 - 1 downto 0);
    trunc_ln647_fu_695_p1 <= or_ln78_fu_675_p2(9 - 1 downto 0);
    trunc_ln76_1_fu_647_p1 <= header_idx_5(3 - 1 downto 0);
    trunc_ln76_2_fu_375_p1 <= header_idx_5(3 - 1 downto 0);
    trunc_ln76_3_fu_379_p1 <= header_idx_5(3 - 1 downto 0);
    trunc_ln76_fu_643_p1 <= header_idx_5(3 - 1 downto 0);
    trunc_ln80_1_fu_799_p4 <= sub_ln80_1_fu_793_p2(10 downto 3);
    trunc_ln82_1_fu_1539_p1 <= p_Result_73_fu_1516_p2(64 - 1 downto 0);
    trunc_ln82_fu_1535_p1 <= p_Result_74_fu_1530_p2(64 - 1 downto 0);

    txEng_shift2pseudoFi_1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, txEng_shift2pseudoFi_1_empty_n, ap_predicate_op10_read_state1, ap_predicate_op15_read_state1, ap_block_pp0_stage0)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op15_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            txEng_shift2pseudoFi_1_blk_n <= txEng_shift2pseudoFi_1_empty_n;
        else 
            txEng_shift2pseudoFi_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    txEng_shift2pseudoFi_1_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op10_read_state1, ap_predicate_op15_read_state1, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op15_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op10_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            txEng_shift2pseudoFi_1_read <= ap_const_logic_1;
        else 
            txEng_shift2pseudoFi_1_read <= ap_const_logic_0;
        end if; 
    end process;


    txEng_tcpMetaFifo_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, txEng_tcpMetaFifo_V_empty_n, ap_predicate_op128_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op128_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            txEng_tcpMetaFifo_V_blk_n <= txEng_tcpMetaFifo_V_empty_n;
        else 
            txEng_tcpMetaFifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    txEng_tcpMetaFifo_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op128_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op128_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            txEng_tcpMetaFifo_V_read <= ap_const_logic_1;
        else 
            txEng_tcpMetaFifo_V_read <= ap_const_logic_0;
        end if; 
    end process;


    txEng_tcpPkgBuffer1_s_8_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, txEng_tcpPkgBuffer1_s_8_full_n, state_1_load_reg_1561, ap_predicate_op187_write_state2, ap_predicate_op204_write_state2, ap_block_pp0_stage0)
    begin
        if ((((state_1_load_reg_1561 = ap_const_lv3_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((state_1_load_reg_1561 = ap_const_lv3_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op204_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op187_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            txEng_tcpPkgBuffer1_s_8_blk_n <= txEng_tcpPkgBuffer1_s_8_full_n;
        else 
            txEng_tcpPkgBuffer1_s_8_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    txEng_tcpPkgBuffer1_s_8_din_assign_proc : process(state_1_load_reg_1561, ap_predicate_op187_write_state2, ap_predicate_op204_write_state2, reg_351, tmp_4_fu_1499_p3, tmp_2_5_fu_1550_p4, ap_condition_267)
    begin
        if ((ap_const_boolean_1 = ap_condition_267)) then
            if ((state_1_load_reg_1561 = ap_const_lv3_1)) then 
                txEng_tcpPkgBuffer1_s_8_din <= tmp_2_5_fu_1550_p4;
            elsif ((ap_predicate_op204_write_state2 = ap_const_boolean_1)) then 
                txEng_tcpPkgBuffer1_s_8_din <= tmp_4_fu_1499_p3;
            elsif ((ap_predicate_op187_write_state2 = ap_const_boolean_1)) then 
                txEng_tcpPkgBuffer1_s_8_din <= reg_351;
            elsif ((state_1_load_reg_1561 = ap_const_lv3_4)) then 
                txEng_tcpPkgBuffer1_s_8_din <= ap_const_lv73_10F00000000B4050402;
            else 
                txEng_tcpPkgBuffer1_s_8_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            txEng_tcpPkgBuffer1_s_8_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    txEng_tcpPkgBuffer1_s_8_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, state_1_load_reg_1561, ap_predicate_op187_write_state2, ap_predicate_op204_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((state_1_load_reg_1561 = ap_const_lv3_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((state_1_load_reg_1561 = ap_const_lv3_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op204_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op187_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            txEng_tcpPkgBuffer1_s_8_write <= ap_const_logic_1;
        else 
            txEng_tcpPkgBuffer1_s_8_write <= ap_const_logic_0;
        end if; 
    end process;


    txEng_tcpTupleFifo_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, txEng_tcpTupleFifo_V_empty_n, ap_predicate_op134_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op134_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            txEng_tcpTupleFifo_V_blk_n <= txEng_tcpTupleFifo_V_empty_n;
        else 
            txEng_tcpTupleFifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    txEng_tcpTupleFifo_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op134_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op134_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            txEng_tcpTupleFifo_V_read <= ap_const_logic_1;
        else 
            txEng_tcpTupleFifo_V_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln1115_fu_981_p2 <= (or_ln1115_fu_975_p2 xor ap_const_lv1_1);
    xor_ln761_fu_1361_p2 <= (tmp_syn_V_fu_1035_p3 xor ap_const_lv1_1);
    xor_ln76_1_fu_585_p2 <= (icmp_ln76_1_fu_401_p2 xor ap_const_lv1_1);
    xor_ln76_fu_901_p2 <= (icmp_ln76_fu_669_p2 xor ap_const_lv1_1);
    zext_ln647_21_fu_1507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln647_13_reg_1612),256));
    zext_ln647_22_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_342_p4),24));
    zext_ln647_23_fu_891_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln647_10_fu_877_p3),256));
    zext_ln647_24_fu_1521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln647_16_reg_1622),256));
    zext_ln647_25_fu_489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln647_13_fu_475_p3),256));
    zext_ln647_26_fu_1449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln647_20_reg_1582),256));
    zext_ln647_27_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_342_p4),24));
    zext_ln647_28_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln647_16_fu_561_p3),256));
    zext_ln647_29_fu_1467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln647_23_reg_1592),256));
    zext_ln647_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln647_7_fu_743_p3),256));
    zext_ln76_1_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Lo_assign_s_fu_383_p3),23));
    zext_ln76_fu_659_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Lo_assign_fu_651_p3),23));
    zext_ln80_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_767_p3),23));
end behav;
