// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module duplicate_stream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_tx_data_req_TVALID,
        tasi_dataFifo_V_din,
        tasi_dataFifo_V_full_n,
        tasi_dataFifo_V_write,
        txApp2txEng_data_str_3_din,
        txApp2txEng_data_str_3_full_n,
        txApp2txEng_data_str_3_write,
        txApp2txEng_data_str_5_din,
        txApp2txEng_data_str_5_full_n,
        txApp2txEng_data_str_5_write,
        txApp2txEng_data_str_6_din,
        txApp2txEng_data_str_6_full_n,
        txApp2txEng_data_str_6_write,
        s_axis_tx_data_req_TDATA,
        s_axis_tx_data_req_TREADY,
        s_axis_tx_data_req_TKEEP,
        s_axis_tx_data_req_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   s_axis_tx_data_req_TVALID;
output  [72:0] tasi_dataFifo_V_din;
input   tasi_dataFifo_V_full_n;
output   tasi_dataFifo_V_write;
output  [63:0] txApp2txEng_data_str_3_din;
input   txApp2txEng_data_str_3_full_n;
output   txApp2txEng_data_str_3_write;
output  [7:0] txApp2txEng_data_str_5_din;
input   txApp2txEng_data_str_5_full_n;
output   txApp2txEng_data_str_5_write;
output  [0:0] txApp2txEng_data_str_6_din;
input   txApp2txEng_data_str_6_full_n;
output   txApp2txEng_data_str_6_write;
input  [63:0] s_axis_tx_data_req_TDATA;
output   s_axis_tx_data_req_TREADY;
input  [7:0] s_axis_tx_data_req_TKEEP;
input  [0:0] s_axis_tx_data_req_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg tasi_dataFifo_V_write;
reg txApp2txEng_data_str_3_write;
reg txApp2txEng_data_str_5_write;
reg txApp2txEng_data_str_6_write;
reg s_axis_tx_data_req_TREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] tmp_nbreadreq_fu_48_p5;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] tmp_reg_110;
wire    io_acc_block_signal_op17;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    s_axis_tx_data_req_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    tasi_dataFifo_V_blk_n;
reg    txApp2txEng_data_str_3_blk_n;
reg    txApp2txEng_data_str_5_blk_n;
reg    txApp2txEng_data_str_6_blk_n;
reg   [63:0] tmp_data_V_reg_114;
reg   [7:0] tmp_keep_V_reg_120;
reg   [0:0] tmp_last_V_reg_126;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_48_p5 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_data_V_reg_114 <= s_axis_tx_data_req_TDATA;
        tmp_keep_V_reg_120 <= s_axis_tx_data_req_TKEEP;
        tmp_last_V_reg_126 <= s_axis_tx_data_req_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_110 <= tmp_nbreadreq_fu_48_p5;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (tmp_nbreadreq_fu_48_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_tx_data_req_TDATA_blk_n = s_axis_tx_data_req_TVALID;
    end else begin
        s_axis_tx_data_req_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_48_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_axis_tx_data_req_TREADY = 1'b1;
    end else begin
        s_axis_tx_data_req_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tasi_dataFifo_V_blk_n = tasi_dataFifo_V_full_n;
    end else begin
        tasi_dataFifo_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tasi_dataFifo_V_write = 1'b1;
    end else begin
        tasi_dataFifo_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        txApp2txEng_data_str_3_blk_n = txApp2txEng_data_str_3_full_n;
    end else begin
        txApp2txEng_data_str_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        txApp2txEng_data_str_3_write = 1'b1;
    end else begin
        txApp2txEng_data_str_3_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        txApp2txEng_data_str_5_blk_n = txApp2txEng_data_str_5_full_n;
    end else begin
        txApp2txEng_data_str_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        txApp2txEng_data_str_5_write = 1'b1;
    end else begin
        txApp2txEng_data_str_5_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        txApp2txEng_data_str_6_blk_n = txApp2txEng_data_str_6_full_n;
    end else begin
        txApp2txEng_data_str_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_110 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        txApp2txEng_data_str_6_write = 1'b1;
    end else begin
        txApp2txEng_data_str_6_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_reg_110 == 1'd1) & (io_acc_block_signal_op17 == 1'b0)) | ((tmp_reg_110 == 1'd1) & (tasi_dataFifo_V_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_48_p5 == 1'd1) & (s_axis_tx_data_req_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_reg_110 == 1'd1) & (io_acc_block_signal_op17 == 1'b0)) | ((tmp_reg_110 == 1'd1) & (tasi_dataFifo_V_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_48_p5 == 1'd1) & (s_axis_tx_data_req_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_reg_110 == 1'd1) & (io_acc_block_signal_op17 == 1'b0)) | ((tmp_reg_110 == 1'd1) & (tasi_dataFifo_V_full_n == 1'b0)))) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_48_p5 == 1'd1) & (s_axis_tx_data_req_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_48_p5 == 1'd1) & (s_axis_tx_data_req_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((tmp_reg_110 == 1'd1) & (io_acc_block_signal_op17 == 1'b0)) | ((tmp_reg_110 == 1'd1) & (tasi_dataFifo_V_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign io_acc_block_signal_op17 = (txApp2txEng_data_str_6_full_n & txApp2txEng_data_str_5_full_n & txApp2txEng_data_str_3_full_n);

assign tasi_dataFifo_V_din = {{{tmp_last_V_reg_126}, {tmp_keep_V_reg_120}}, {tmp_data_V_reg_114}};

assign tmp_nbreadreq_fu_48_p5 = s_axis_tx_data_req_TVALID;

assign txApp2txEng_data_str_3_din = tmp_data_V_reg_114;

assign txApp2txEng_data_str_5_din = tmp_keep_V_reg_120;

assign txApp2txEng_data_str_6_din = tmp_last_V_reg_126;

endmodule //duplicate_stream
