// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rx_app_stream_if (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        appRxDataReq_V_TVALID,
        rxSar2rxApp_upd_rsp_s_16_dout,
        rxSar2rxApp_upd_rsp_s_16_empty_n,
        rxSar2rxApp_upd_rsp_s_16_read,
        rxApp2rxSar_upd_req_s_19_din,
        rxApp2rxSar_upd_req_s_19_full_n,
        rxApp2rxSar_upd_req_s_19_write,
        rxBufferReadCmd_V_V_din,
        rxBufferReadCmd_V_V_full_n,
        rxBufferReadCmd_V_V_write,
        appRxDataRspMetadata_V_V_TREADY,
        appRxDataReq_V_TDATA,
        appRxDataReq_V_TREADY,
        appRxDataRspMetadata_V_V_TDATA,
        appRxDataRspMetadata_V_V_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   appRxDataReq_V_TVALID;
input  [32:0] rxSar2rxApp_upd_rsp_s_16_dout;
input   rxSar2rxApp_upd_rsp_s_16_empty_n;
output   rxSar2rxApp_upd_rsp_s_16_read;
output  [32:0] rxApp2rxSar_upd_req_s_19_din;
input   rxApp2rxSar_upd_req_s_19_full_n;
output   rxApp2rxSar_upd_req_s_19_write;
output  [0:0] rxBufferReadCmd_V_V_din;
input   rxBufferReadCmd_V_V_full_n;
output   rxBufferReadCmd_V_V_write;
input   appRxDataRspMetadata_V_V_TREADY;
input  [31:0] appRxDataReq_V_TDATA;
output   appRxDataReq_V_TREADY;
output  [15:0] appRxDataRspMetadata_V_V_TDATA;
output   appRxDataRspMetadata_V_V_TVALID;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rxSar2rxApp_upd_rsp_s_16_read;
reg[32:0] rxApp2rxSar_upd_req_s_19_din;
reg rxApp2rxSar_upd_req_s_19_write;
reg rxBufferReadCmd_V_V_write;
reg appRxDataReq_V_TREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] tmp_91_nbreadreq_fu_72_p3;
reg    ap_predicate_op8_read_state1;
wire   [0:0] tmp_nbreadreq_fu_86_p3;
reg    ap_predicate_op17_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] rasi_fsmState_V_load_reg_205;
reg   [0:0] tmp_91_reg_209;
reg   [0:0] icmp_ln883_reg_218;
reg    ap_predicate_op22_write_state2;
reg   [0:0] tmp_reg_222;
reg    ap_predicate_op24_write_state2;
reg    ap_predicate_op28_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    appRxDataRspMetadata_V_V_1_ack_in;
reg    ap_predicate_op23_write_state2;
reg    ap_block_state2_io;
wire    appRxDataRspMetadata_V_V_1_ack_out;
reg   [1:0] appRxDataRspMetadata_V_V_1_state;
reg    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] rasi_fsmState_V_load_reg_205_pp0_iter1_reg;
reg   [0:0] tmp_reg_222_pp0_iter1_reg;
reg    ap_predicate_op38_write_state3;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] appRxDataRspMetadata_V_V_1_data_out;
reg    appRxDataRspMetadata_V_V_1_vld_in;
wire    appRxDataRspMetadata_V_V_1_vld_out;
reg   [15:0] appRxDataRspMetadata_V_V_1_payload_A;
reg   [15:0] appRxDataRspMetadata_V_V_1_payload_B;
reg    appRxDataRspMetadata_V_V_1_sel_rd;
reg    appRxDataRspMetadata_V_V_1_sel_wr;
wire    appRxDataRspMetadata_V_V_1_sel;
wire    appRxDataRspMetadata_V_V_1_load_A;
wire    appRxDataRspMetadata_V_V_1_load_B;
wire    appRxDataRspMetadata_V_V_1_state_cmp_full;
reg   [0:0] rasi_fsmState_V;
reg   [15:0] rasi_readLength_V;
reg    appRxDataReq_V_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    appRxDataRspMetadata_V_V_TDATA_blk_n;
reg    rxApp2rxSar_upd_req_s_19_blk_n;
reg    rxSar2rxApp_upd_rsp_s_16_blk_n;
reg    rxBufferReadCmd_V_V_blk_n;
wire   [15:0] tmp_sessionID_V_6_fu_126_p1;
reg   [15:0] tmp_sessionID_V_6_reg_213;
wire   [0:0] icmp_ln883_fu_140_p2;
wire   [15:0] tmp_V_fu_158_p1;
reg   [15:0] tmp_V_reg_226;
reg   [15:0] tmp_appd_V_load_new_s_reg_232;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] tmp_length_V_load_ne_fu_130_p4;
wire   [32:0] tmp_1_fu_178_p3;
reg    ap_block_pp0_stage0_01001;
wire   [32:0] tmp_3_fu_195_p4;
wire   [15:0] tmp_appd_V_fu_190_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_251;
reg    ap_condition_145;
reg    ap_condition_274;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 appRxDataRspMetadata_V_V_1_state = 2'd0;
#0 appRxDataRspMetadata_V_V_1_sel_rd = 1'b0;
#0 appRxDataRspMetadata_V_V_1_sel_wr = 1'b0;
#0 rasi_fsmState_V = 1'd0;
#0 rasi_readLength_V = 16'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        appRxDataRspMetadata_V_V_1_sel_rd <= 1'b0;
    end else begin
        if (((appRxDataRspMetadata_V_V_1_vld_out == 1'b1) & (appRxDataRspMetadata_V_V_1_ack_out == 1'b1))) begin
            appRxDataRspMetadata_V_V_1_sel_rd <= ~appRxDataRspMetadata_V_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        appRxDataRspMetadata_V_V_1_sel_wr <= 1'b0;
    end else begin
        if (((appRxDataRspMetadata_V_V_1_vld_in == 1'b1) & (appRxDataRspMetadata_V_V_1_ack_in == 1'b1))) begin
            appRxDataRspMetadata_V_V_1_sel_wr <= ~appRxDataRspMetadata_V_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        appRxDataRspMetadata_V_V_1_state <= 2'd0;
    end else begin
        if ((((appRxDataRspMetadata_V_V_1_vld_in == 1'b0) & (appRxDataRspMetadata_V_V_1_ack_out == 1'b1) & (appRxDataRspMetadata_V_V_1_state == 2'd3)) | ((appRxDataRspMetadata_V_V_1_vld_in == 1'b0) & (appRxDataRspMetadata_V_V_1_state == 2'd2)))) begin
            appRxDataRspMetadata_V_V_1_state <= 2'd2;
        end else if ((((appRxDataRspMetadata_V_V_TREADY == 1'b0) & (appRxDataRspMetadata_V_V_1_state == 2'd1)) | ((appRxDataRspMetadata_V_V_TREADY == 1'b0) & (appRxDataRspMetadata_V_V_1_vld_in == 1'b1) & (appRxDataRspMetadata_V_V_1_state == 2'd3)))) begin
            appRxDataRspMetadata_V_V_1_state <= 2'd1;
        end else if ((((appRxDataRspMetadata_V_V_1_ack_out == 1'b1) & (appRxDataRspMetadata_V_V_1_state == 2'd1)) | (~((appRxDataRspMetadata_V_V_1_vld_in == 1'b0) & (appRxDataRspMetadata_V_V_1_ack_out == 1'b1)) & ~((appRxDataRspMetadata_V_V_TREADY == 1'b0) & (appRxDataRspMetadata_V_V_1_vld_in == 1'b1)) & (appRxDataRspMetadata_V_V_1_state == 2'd3)) | ((appRxDataRspMetadata_V_V_1_vld_in == 1'b1) & (appRxDataRspMetadata_V_V_1_state == 2'd2)))) begin
            appRxDataRspMetadata_V_V_1_state <= 2'd3;
        end else begin
            appRxDataRspMetadata_V_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_145)) begin
        if (((tmp_nbreadreq_fu_86_p3 == 1'd1) & (rasi_fsmState_V == 1'd1))) begin
            rasi_fsmState_V <= 1'd0;
        end else if ((1'b1 == ap_condition_251)) begin
            rasi_fsmState_V <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((appRxDataRspMetadata_V_V_1_load_A == 1'b1)) begin
        appRxDataRspMetadata_V_V_1_payload_A <= tmp_V_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if ((appRxDataRspMetadata_V_V_1_load_B == 1'b1)) begin
        appRxDataRspMetadata_V_V_1_payload_B <= tmp_V_reg_226;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_91_nbreadreq_fu_72_p3 == 1'd1) & (rasi_fsmState_V == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln883_reg_218 <= icmp_ln883_fu_140_p2;
        tmp_sessionID_V_6_reg_213 <= tmp_sessionID_V_6_fu_126_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rasi_fsmState_V_load_reg_205 <= rasi_fsmState_V;
        rasi_fsmState_V_load_reg_205_pp0_iter1_reg <= rasi_fsmState_V_load_reg_205;
        tmp_reg_222_pp0_iter1_reg <= tmp_reg_222;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_91_nbreadreq_fu_72_p3 == 1'd1) & (icmp_ln883_fu_140_p2 == 1'd0) & (rasi_fsmState_V == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rasi_readLength_V <= {{appRxDataReq_V_TDATA[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((rasi_fsmState_V == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_91_reg_209 <= tmp_91_nbreadreq_fu_72_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_86_p3 == 1'd1) & (rasi_fsmState_V == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_V_reg_226 <= tmp_V_fu_158_p1;
        tmp_appd_V_load_new_s_reg_232 <= {{rxSar2rxApp_upd_rsp_s_16_dout[31:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((rasi_fsmState_V == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_222 <= tmp_nbreadreq_fu_86_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op8_read_state1 == 1'b1))) begin
        appRxDataReq_V_TDATA_blk_n = appRxDataReq_V_TVALID;
    end else begin
        appRxDataReq_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op8_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        appRxDataReq_V_TREADY = 1'b1;
    end else begin
        appRxDataReq_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((appRxDataRspMetadata_V_V_1_sel == 1'b1)) begin
        appRxDataRspMetadata_V_V_1_data_out = appRxDataRspMetadata_V_V_1_payload_B;
    end else begin
        appRxDataRspMetadata_V_V_1_data_out = appRxDataRspMetadata_V_V_1_payload_A;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op23_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        appRxDataRspMetadata_V_V_1_vld_in = 1'b1;
    end else begin
        appRxDataRspMetadata_V_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op23_write_state2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op38_write_state3 == 1'b1)))) begin
        appRxDataRspMetadata_V_V_TDATA_blk_n = appRxDataRspMetadata_V_V_1_state[1'd1];
    end else begin
        appRxDataRspMetadata_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op28_write_state2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op22_write_state2 == 1'b1)))) begin
        rxApp2rxSar_upd_req_s_19_blk_n = rxApp2rxSar_upd_req_s_19_full_n;
    end else begin
        rxApp2rxSar_upd_req_s_19_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_274)) begin
        if ((ap_predicate_op28_write_state2 == 1'b1)) begin
            rxApp2rxSar_upd_req_s_19_din = tmp_3_fu_195_p4;
        end else if ((ap_predicate_op22_write_state2 == 1'b1)) begin
            rxApp2rxSar_upd_req_s_19_din = tmp_1_fu_178_p3;
        end else begin
            rxApp2rxSar_upd_req_s_19_din = 'bx;
        end
    end else begin
        rxApp2rxSar_upd_req_s_19_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op28_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op22_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        rxApp2rxSar_upd_req_s_19_write = 1'b1;
    end else begin
        rxApp2rxSar_upd_req_s_19_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op24_write_state2 == 1'b1))) begin
        rxBufferReadCmd_V_V_blk_n = rxBufferReadCmd_V_V_full_n;
    end else begin
        rxBufferReadCmd_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op24_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rxBufferReadCmd_V_V_write = 1'b1;
    end else begin
        rxBufferReadCmd_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op17_read_state1 == 1'b1))) begin
        rxSar2rxApp_upd_rsp_s_16_blk_n = rxSar2rxApp_upd_rsp_s_16_empty_n;
    end else begin
        rxSar2rxApp_upd_rsp_s_16_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op17_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rxSar2rxApp_upd_rsp_s_16_read = 1'b1;
    end else begin
        rxSar2rxApp_upd_rsp_s_16_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((rxBufferReadCmd_V_V_full_n == 1'b0) & (ap_predicate_op24_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op28_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)))) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxSar2rxApp_upd_rsp_s_16_empty_n == 1'b0) & (ap_predicate_op17_read_state1 == 1'b1)) | ((appRxDataReq_V_TVALID == 1'b0) & (ap_predicate_op8_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((appRxDataRspMetadata_V_V_1_state == 2'd1) | ((appRxDataRspMetadata_V_V_TREADY == 1'b0) & (appRxDataRspMetadata_V_V_1_state == 2'd3)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxSar2rxApp_upd_rsp_s_16_empty_n == 1'b0) & (ap_predicate_op17_read_state1 == 1'b1)) | ((appRxDataReq_V_TVALID == 1'b0) & (ap_predicate_op8_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | (appRxDataRspMetadata_V_V_1_state == 2'd1) | ((appRxDataRspMetadata_V_V_TREADY == 1'b0) & (appRxDataRspMetadata_V_V_1_state == 2'd3)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((rxBufferReadCmd_V_V_full_n == 1'b0) & (ap_predicate_op24_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op28_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxSar2rxApp_upd_rsp_s_16_empty_n == 1'b0) & (ap_predicate_op17_read_state1 == 1'b1)) | ((appRxDataReq_V_TVALID == 1'b0) & (ap_predicate_op8_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | (appRxDataRspMetadata_V_V_1_state == 2'd1) | ((appRxDataRspMetadata_V_V_TREADY == 1'b0) & (appRxDataRspMetadata_V_V_1_state == 2'd3)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((rxBufferReadCmd_V_V_full_n == 1'b0) & (ap_predicate_op24_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op28_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((rxSar2rxApp_upd_rsp_s_16_empty_n == 1'b0) & (ap_predicate_op17_read_state1 == 1'b1)) | ((appRxDataReq_V_TVALID == 1'b0) & (ap_predicate_op8_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_io = ((appRxDataRspMetadata_V_V_1_ack_in == 1'b0) & (ap_predicate_op23_write_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((rxBufferReadCmd_V_V_full_n == 1'b0) & (ap_predicate_op24_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op28_write_state2 == 1'b1)) | ((rxApp2rxSar_upd_req_s_19_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = ((appRxDataRspMetadata_V_V_1_ack_in == 1'b0) & (ap_predicate_op38_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((appRxDataRspMetadata_V_V_1_state == 2'd1) | ((appRxDataRspMetadata_V_V_TREADY == 1'b0) & (appRxDataRspMetadata_V_V_1_state == 2'd3)));
end

always @ (*) begin
    ap_condition_145 = ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_251 = ((tmp_91_nbreadreq_fu_72_p3 == 1'd1) & (icmp_ln883_fu_140_p2 == 1'd0) & (rasi_fsmState_V == 1'd0));
end

always @ (*) begin
    ap_condition_274 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_predicate_op17_read_state1 = ((tmp_nbreadreq_fu_86_p3 == 1'd1) & (rasi_fsmState_V == 1'd1));
end

always @ (*) begin
    ap_predicate_op22_write_state2 = ((tmp_91_reg_209 == 1'd1) & (icmp_ln883_reg_218 == 1'd0) & (rasi_fsmState_V_load_reg_205 == 1'd0));
end

always @ (*) begin
    ap_predicate_op23_write_state2 = ((tmp_reg_222 == 1'd1) & (rasi_fsmState_V_load_reg_205 == 1'd1));
end

always @ (*) begin
    ap_predicate_op24_write_state2 = ((tmp_reg_222 == 1'd1) & (rasi_fsmState_V_load_reg_205 == 1'd1));
end

always @ (*) begin
    ap_predicate_op28_write_state2 = ((tmp_reg_222 == 1'd1) & (rasi_fsmState_V_load_reg_205 == 1'd1));
end

always @ (*) begin
    ap_predicate_op38_write_state3 = ((tmp_reg_222_pp0_iter1_reg == 1'd1) & (rasi_fsmState_V_load_reg_205_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op8_read_state1 = ((tmp_91_nbreadreq_fu_72_p3 == 1'd1) & (rasi_fsmState_V == 1'd0));
end

assign appRxDataRspMetadata_V_V_1_ack_in = appRxDataRspMetadata_V_V_1_state[1'd1];

assign appRxDataRspMetadata_V_V_1_ack_out = appRxDataRspMetadata_V_V_TREADY;

assign appRxDataRspMetadata_V_V_1_load_A = (~appRxDataRspMetadata_V_V_1_sel_wr & appRxDataRspMetadata_V_V_1_state_cmp_full);

assign appRxDataRspMetadata_V_V_1_load_B = (appRxDataRspMetadata_V_V_1_state_cmp_full & appRxDataRspMetadata_V_V_1_sel_wr);

assign appRxDataRspMetadata_V_V_1_sel = appRxDataRspMetadata_V_V_1_sel_rd;

assign appRxDataRspMetadata_V_V_1_state_cmp_full = ((appRxDataRspMetadata_V_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign appRxDataRspMetadata_V_V_1_vld_out = appRxDataRspMetadata_V_V_1_state[1'd0];

assign appRxDataRspMetadata_V_V_TDATA = appRxDataRspMetadata_V_V_1_data_out;

assign appRxDataRspMetadata_V_V_TVALID = appRxDataRspMetadata_V_V_1_state[1'd0];

assign icmp_ln883_fu_140_p2 = ((tmp_length_V_load_ne_fu_130_p4 == 16'd0) ? 1'b1 : 1'b0);

assign rxBufferReadCmd_V_V_din = 1'd1;

assign tmp_1_fu_178_p3 = {{17'd0}, {tmp_sessionID_V_6_reg_213}};

assign tmp_3_fu_195_p4 = {{{{1'd1}, {tmp_appd_V_fu_190_p2}}}, {tmp_V_reg_226}};

assign tmp_91_nbreadreq_fu_72_p3 = appRxDataReq_V_TVALID;

assign tmp_V_fu_158_p1 = rxSar2rxApp_upd_rsp_s_16_dout[15:0];

assign tmp_appd_V_fu_190_p2 = (tmp_appd_V_load_new_s_reg_232 + rasi_readLength_V);

assign tmp_length_V_load_ne_fu_130_p4 = {{appRxDataReq_V_TDATA[31:16]}};

assign tmp_nbreadreq_fu_86_p3 = rxSar2rxApp_upd_rsp_s_16_empty_n;

assign tmp_sessionID_V_6_fu_126_p1 = appRxDataReq_V_TDATA[15:0];

endmodule //rx_app_stream_if
