-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity check_icmp_checksum is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_TVALID : IN STD_LOGIC;
    packageBuffer1_V_din : OUT STD_LOGIC_VECTOR (72 downto 0);
    packageBuffer1_V_full_n : IN STD_LOGIC;
    packageBuffer1_V_write : OUT STD_LOGIC;
    validFifo_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    validFifo_V_full_n : IN STD_LOGIC;
    validFifo_V_write : OUT STD_LOGIC;
    checksumStreams_V_V_s_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    checksumStreams_V_V_s_full_n : IN STD_LOGIC;
    checksumStreams_V_V_s_write : OUT STD_LOGIC;
    s_axis_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    s_axis_TREADY : OUT STD_LOGIC;
    s_axis_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of check_icmp_checksum is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_8 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_const_lv9_FF : STD_LOGIC_VECTOR (8 downto 0) := "011111111";
    constant ap_const_lv17_1FFF8 : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal cics_writeLastOne_lo_load_fu_286_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal cics_computeCs_load_load_fu_290_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_nbreadreq_fu_162_p5 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op18_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal cics_writeLastOne_lo_reg_1400 : STD_LOGIC_VECTOR (0 downto 0);
    signal cics_computeCs_load_reg_1404 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1408 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_1_reg_1436 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_predicate_op212_write_state2 : BOOLEAN;
    signal ap_predicate_op218_write_state2 : BOOLEAN;
    signal ap_predicate_op228_write_state2 : BOOLEAN;
    signal t_V_reg_1468 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln91_1_reg_1472 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op235_write_state2 : BOOLEAN;
    signal ap_predicate_op237_write_state2 : BOOLEAN;
    signal ap_predicate_op239_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal cics_writeLastOne : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal cics_prevWord_data_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal cics_prevWord_keep_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal cics_prevWord_last_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal cics_computeCs : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal cics_sums_V_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cics_sums_V_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal cics_sums_V_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cics_sums_V_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal icmpChecksum_V : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal icmpType_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal icmpCode_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal cics_state_V : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal cics_wordCount_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal s_axis_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal packageBuffer1_V_blk_n : STD_LOGIC;
    signal validFifo_V_blk_n : STD_LOGIC;
    signal checksumStreams_V_V_s_blk_n : STD_LOGIC;
    signal tmp_data_V_26_reg_1412 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_keep_V_20_reg_1422 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_last_V_17_fu_343_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_17_reg_1427 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_fu_347_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_1_load_fu_351_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln879_3_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_4_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_643_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_5_fu_767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_773_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_6_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_893_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_load_fu_1022_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln91_1_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln700_14_fu_997_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_empty_52_phi_fu_220_p8 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_10_fu_1296_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_52_reg_217 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_52_reg_217 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln214_9_fu_403_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_23_fu_817_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_21_fu_865_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln214_6_fu_547_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln214_5_fu_617_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal r_V_3_fu_1066_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln214_3_fu_1112_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln214_fu_1156_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln214_11_fu_451_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_27_fu_937_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_25_fu_985_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_19_fu_687_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_17_fu_745_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_5_fu_1190_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_1253_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_275_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln214_4_fu_1379_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_230_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_239_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln700_6_fu_1202_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_1267_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_1_fu_1308_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal tmp_3_fu_1319_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal tmp12_fu_1389_p4 : STD_LOGIC_VECTOR (72 downto 0);
    signal p_Result_123_i_fu_367_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_fu_298_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln700_3_fu_375_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_3_fu_379_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_28_fu_385_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_10_fu_393_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_8_fu_397_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_257_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_248_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_123_1_i_fu_415_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_1_fu_310_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln700_4_fu_423_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_4_fu_427_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_29_fu_433_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_11_fu_441_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_10_fu_445_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln647_5_fu_487_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln647_9_fu_497_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_134_i_fu_501_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_6_fu_509_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_7_fu_517_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_31_fu_523_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_13_fu_531_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln700_3_fu_513_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_14_fu_535_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_15_fu_541_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln647_8_fu_567_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i_fu_557_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_131_i_fu_571_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_5_fu_579_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_5_fu_587_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_30_fu_593_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_12_fu_601_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln700_2_fu_583_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_12_fu_605_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_13_fu_611_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_127_1_i_fu_627_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_266_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_134_1_i_fu_651_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_8_fu_659_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln700_2_fu_318_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_9_fu_663_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_34_fu_669_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_15_fu_677_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_18_fu_681_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_128_1_i_fu_699_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_131_1_i_fu_709_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_7_fu_717_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_8_fu_721_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_32_fu_727_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_14_fu_735_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_16_fu_739_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_127_2_i_fu_757_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_134_2_i_fu_781_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_10_fu_789_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_11_fu_793_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_37_fu_799_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_17_fu_807_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_22_fu_811_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_131_2_i_fu_829_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_9_fu_837_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_10_fu_841_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_35_fu_847_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_16_fu_855_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_20_fu_859_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_127_3_i_fu_877_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_134_3_i_fu_901_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_12_fu_909_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_13_fu_913_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_40_fu_919_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_19_fu_927_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_26_fu_931_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_131_3_i_fu_949_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_11_fu_957_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_12_fu_961_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_38_fu_967_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_18_fu_975_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_24_fu_979_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln647_fu_1026_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln879_1_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_2_fu_1042_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln91_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_2_fu_1082_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_26_fu_1088_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_9_fu_1096_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln700_1_fu_1078_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_6_fu_1100_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_7_fu_1106_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln700_fu_1126_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_24_fu_1132_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_7_fu_1140_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln700_fu_1122_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_fu_1144_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_3_fu_1150_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln700_1_fu_1166_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_25_fu_1172_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_8_fu_1180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_4_fu_1184_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_27_i_fu_1244_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln647_7_fu_1241_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln647_6_fu_1237_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_29_i_fu_1278_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_i_fu_1288_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln701_fu_1351_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_27_fu_1357_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln214_fu_1365_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln214_20_fu_1369_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln214_fu_1373_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_373 : BOOLEAN;
    signal ap_condition_1011 : BOOLEAN;
    signal ap_condition_1009 : BOOLEAN;
    signal ap_condition_1017 : BOOLEAN;
    signal ap_condition_1024 : BOOLEAN;
    signal ap_condition_1027 : BOOLEAN;
    signal ap_condition_1034 : BOOLEAN;
    signal ap_condition_1037 : BOOLEAN;
    signal ap_condition_1043 : BOOLEAN;
    signal ap_condition_1046 : BOOLEAN;
    signal ap_condition_371 : BOOLEAN;
    signal ap_condition_1052 : BOOLEAN;
    signal ap_condition_1055 : BOOLEAN;
    signal ap_condition_249 : BOOLEAN;
    signal ap_condition_137 : BOOLEAN;
    signal ap_condition_384 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_empty_52_reg_217_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((t_V_1_load_fu_351_p1 = ap_const_lv16_1) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((t_V_1_load_fu_351_p1 = ap_const_lv16_0) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                ap_phi_reg_pp0_iter1_empty_52_reg_217 <= s_axis_TDATA;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ap_phi_reg_pp0_iter1_empty_52_reg_217 <= ap_phi_reg_pp0_iter0_empty_52_reg_217;
            end if; 
        end if;
    end process;

    cics_computeCs_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1009)) then
                if (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (t_V_load_fu_1022_p1 = ap_const_lv2_3))) then 
                    cics_computeCs <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_1011)) then 
                    cics_computeCs <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    cics_sums_V_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1009)) then
                if (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (t_V_load_fu_1022_p1 = ap_const_lv2_0))) then 
                    cics_sums_V_0 <= zext_ln214_fu_1156_p1;
                elsif (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (t_V_load_fu_1022_p1 = ap_const_lv2_1))) then 
                    cics_sums_V_0 <= zext_ln214_3_fu_1112_p1;
                elsif (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (t_V_load_fu_1022_p1 = ap_const_lv2_2))) then 
                    cics_sums_V_0 <= r_V_3_fu_1066_p2;
                elsif ((ap_const_boolean_1 = ap_condition_1027)) then 
                    cics_sums_V_0 <= zext_ln214_5_fu_617_p1;
                elsif ((ap_const_boolean_1 = ap_condition_1024)) then 
                    cics_sums_V_0 <= zext_ln214_6_fu_547_p1;
                elsif ((ap_const_boolean_1 = ap_condition_1017)) then 
                    cics_sums_V_0 <= ap_const_lv17_0;
                end if;
            end if; 
        end if;
    end process;

    cics_sums_V_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1009)) then
                if (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (t_V_load_fu_1022_p1 = ap_const_lv2_0))) then 
                    cics_sums_V_1 <= add_ln214_5_fu_1190_p2;
                elsif ((ap_const_boolean_1 = ap_condition_1037)) then 
                    cics_sums_V_1 <= add_ln214_17_fu_745_p2;
                elsif ((ap_const_boolean_1 = ap_condition_1034)) then 
                    cics_sums_V_1 <= add_ln214_19_fu_687_p2;
                elsif ((ap_const_boolean_1 = ap_condition_1017)) then 
                    cics_sums_V_1 <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;

    cics_sums_V_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_371)) then
                if ((ap_const_boolean_1 = ap_condition_1046)) then 
                    cics_sums_V_2 <= add_ln214_21_fu_865_p2;
                elsif ((ap_const_boolean_1 = ap_condition_1043)) then 
                    cics_sums_V_2 <= add_ln214_23_fu_817_p2;
                elsif ((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) then 
                    cics_sums_V_2 <= ap_const_lv16_0;
                elsif ((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) then 
                    cics_sums_V_2 <= add_ln214_9_fu_403_p2;
                end if;
            end if; 
        end if;
    end process;

    cics_sums_V_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_371)) then
                if ((ap_const_boolean_1 = ap_condition_1055)) then 
                    cics_sums_V_3 <= add_ln214_25_fu_985_p2;
                elsif ((ap_const_boolean_1 = ap_condition_1052)) then 
                    cics_sums_V_3 <= add_ln214_27_fu_937_p2;
                elsif ((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) then 
                    cics_sums_V_3 <= ap_const_lv16_0;
                elsif ((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) then 
                    cics_sums_V_3 <= add_ln214_11_fu_451_p2;
                end if;
            end if; 
        end if;
    end process;

    cics_writeLastOne_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_137)) then
                if ((cics_writeLastOne_lo_load_fu_286_p1 = ap_const_lv1_1)) then 
                    cics_writeLastOne <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_249)) then 
                    cics_writeLastOne <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    icmpChecksum_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((t_V_reg_1468 = ap_const_lv2_1) and (cics_computeCs_load_reg_1404 = ap_const_lv1_1) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                icmpChecksum_V <= zext_ln214_4_fu_1379_p1;
            elsif ((((t_V_reg_1468 = ap_const_lv2_0) and (cics_computeCs_load_reg_1404 = ap_const_lv1_1) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((t_V_reg_1468 = ap_const_lv2_2) and (cics_computeCs_load_reg_1404 = ap_const_lv1_1) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                icmpChecksum_V <= grp_fu_275_p2;
            elsif (((t_V_1_reg_1436 = ap_const_lv16_2) and (tmp_reg_1408 = ap_const_lv1_1) and (cics_computeCs_load_reg_1404 = ap_const_lv1_0) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                icmpChecksum_V <= p_Result_s_fu_1253_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (cics_writeLastOne = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (t_V_load_fu_1022_p1 = ap_const_lv2_3))) then
                and_ln91_1_reg_1472 <= and_ln91_1_fu_1054_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cics_writeLastOne = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cics_computeCs_load_reg_1404 <= cics_computeCs;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_reg_1408 = ap_const_lv1_1) and (cics_computeCs_load_reg_1404 = ap_const_lv1_0) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cics_prevWord_data_V <= ap_phi_mux_empty_52_phi_fu_220_p8;
                cics_prevWord_keep_V <= tmp_keep_V_20_reg_1422;
                cics_prevWord_last_V <= tmp_last_V_17_reg_1427;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cics_state_V <= add_ln700_6_fu_1202_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cics_wordCount_V <= ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cics_writeLastOne_lo_reg_1400 <= cics_writeLastOne;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((t_V_1_load_fu_351_p1 = ap_const_lv16_2) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmpCode_V <= s_axis_TDATA(47 downto 40);
                icmpType_V <= s_axis_TDATA(39 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                t_V_1_reg_1436 <= cics_wordCount_V;
                tmp_data_V_26_reg_1412 <= s_axis_TDATA;
                tmp_keep_V_20_reg_1422 <= s_axis_TKEEP;
                tmp_last_V_17_reg_1427 <= s_axis_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cics_computeCs_load_load_fu_290_p1 = ap_const_lv1_1) and (cics_writeLastOne = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                t_V_reg_1468 <= cics_state_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_1408 <= tmp_nbreadreq_fu_162_p5;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln214_10_fu_445_p2 <= std_logic_vector(unsigned(zext_ln214_11_fu_441_p1) + unsigned(p_Result_123_1_i_fu_415_p3));
    add_ln214_11_fu_451_p2 <= std_logic_vector(unsigned(cics_sums_V_3) + unsigned(add_ln214_10_fu_445_p2));
    add_ln214_12_fu_605_p2 <= std_logic_vector(unsigned(zext_ln214_12_fu_601_p1) + unsigned(p_Result_131_i_fu_571_p3));
    add_ln214_13_fu_611_p2 <= std_logic_vector(unsigned(trunc_ln700_2_fu_583_p1) + unsigned(add_ln214_12_fu_605_p2));
    add_ln214_14_fu_535_p2 <= std_logic_vector(unsigned(zext_ln214_13_fu_531_p1) + unsigned(p_Result_134_i_fu_501_p3));
    add_ln214_15_fu_541_p2 <= std_logic_vector(unsigned(trunc_ln700_3_fu_513_p1) + unsigned(add_ln214_14_fu_535_p2));
    add_ln214_16_fu_739_p2 <= std_logic_vector(unsigned(p_Result_131_1_i_fu_709_p3) + unsigned(zext_ln214_14_fu_735_p1));
    add_ln214_17_fu_745_p2 <= std_logic_vector(unsigned(add_ln214_16_fu_739_p2) + unsigned(cics_sums_V_1));
    add_ln214_18_fu_681_p2 <= std_logic_vector(unsigned(p_Result_134_1_i_fu_651_p3) + unsigned(zext_ln214_15_fu_677_p1));
    add_ln214_19_fu_687_p2 <= std_logic_vector(unsigned(add_ln214_18_fu_681_p2) + unsigned(cics_sums_V_1));
    add_ln214_20_fu_859_p2 <= std_logic_vector(unsigned(p_Result_131_2_i_fu_829_p3) + unsigned(zext_ln214_16_fu_855_p1));
    add_ln214_21_fu_865_p2 <= std_logic_vector(unsigned(add_ln214_20_fu_859_p2) + unsigned(cics_sums_V_2));
    add_ln214_22_fu_811_p2 <= std_logic_vector(unsigned(p_Result_134_2_i_fu_781_p3) + unsigned(zext_ln214_17_fu_807_p1));
    add_ln214_23_fu_817_p2 <= std_logic_vector(unsigned(add_ln214_22_fu_811_p2) + unsigned(cics_sums_V_2));
    add_ln214_24_fu_979_p2 <= std_logic_vector(unsigned(p_Result_131_3_i_fu_949_p3) + unsigned(zext_ln214_18_fu_975_p1));
    add_ln214_25_fu_985_p2 <= std_logic_vector(unsigned(add_ln214_24_fu_979_p2) + unsigned(cics_sums_V_3));
    add_ln214_26_fu_931_p2 <= std_logic_vector(unsigned(p_Result_134_3_i_fu_901_p3) + unsigned(zext_ln214_19_fu_927_p1));
    add_ln214_27_fu_937_p2 <= std_logic_vector(unsigned(add_ln214_26_fu_931_p2) + unsigned(cics_sums_V_3));
    add_ln214_3_fu_1150_p2 <= std_logic_vector(unsigned(cics_sums_V_2) + unsigned(add_ln214_fu_1144_p2));
    add_ln214_4_fu_1184_p2 <= std_logic_vector(unsigned(zext_ln214_8_fu_1180_p1) + unsigned(cics_sums_V_3));
    add_ln214_5_fu_1190_p2 <= std_logic_vector(unsigned(cics_sums_V_1) + unsigned(add_ln214_4_fu_1184_p2));
    add_ln214_6_fu_1100_p2 <= std_logic_vector(unsigned(zext_ln214_9_fu_1096_p1) + unsigned(trunc_ln700_1_fu_1078_p1));
    add_ln214_7_fu_1106_p2 <= std_logic_vector(unsigned(cics_sums_V_1) + unsigned(add_ln214_6_fu_1100_p2));
    add_ln214_8_fu_397_p2 <= std_logic_vector(unsigned(zext_ln214_10_fu_393_p1) + unsigned(p_Result_123_i_fu_367_p3));
    add_ln214_9_fu_403_p2 <= std_logic_vector(unsigned(cics_sums_V_2) + unsigned(add_ln214_8_fu_397_p2));
    add_ln214_fu_1144_p2 <= std_logic_vector(unsigned(zext_ln214_7_fu_1140_p1) + unsigned(trunc_ln700_fu_1122_p1));
    add_ln700_10_fu_841_p2 <= std_logic_vector(unsigned(zext_ln700_9_fu_837_p1) + unsigned(zext_ln700_fu_298_p1));
    add_ln700_11_fu_793_p2 <= std_logic_vector(unsigned(zext_ln700_10_fu_789_p1) + unsigned(zext_ln700_fu_298_p1));
    add_ln700_12_fu_961_p2 <= std_logic_vector(unsigned(zext_ln700_11_fu_957_p1) + unsigned(zext_ln700_1_fu_310_p1));
    add_ln700_13_fu_913_p2 <= std_logic_vector(unsigned(zext_ln700_12_fu_909_p1) + unsigned(zext_ln700_1_fu_310_p1));
    add_ln700_14_fu_997_p2 <= std_logic_vector(unsigned(cics_wordCount_V) + unsigned(ap_const_lv16_1));
    add_ln700_1_fu_1166_p2 <= std_logic_vector(unsigned(zext_ln700_2_fu_318_p1) + unsigned(zext_ln700_1_fu_310_p1));
    add_ln700_2_fu_1082_p2 <= std_logic_vector(unsigned(zext_ln700_2_fu_318_p1) + unsigned(cics_sums_V_0));
    add_ln700_3_fu_379_p2 <= std_logic_vector(unsigned(zext_ln700_fu_298_p1) + unsigned(zext_ln700_3_fu_375_p1));
    add_ln700_4_fu_427_p2 <= std_logic_vector(unsigned(zext_ln700_1_fu_310_p1) + unsigned(zext_ln700_4_fu_423_p1));
    add_ln700_5_fu_587_p2 <= std_logic_vector(unsigned(zext_ln700_5_fu_579_p1) + unsigned(cics_sums_V_0));
    add_ln700_6_fu_1202_p2 <= std_logic_vector(unsigned(cics_state_V) + unsigned(ap_const_lv2_1));
    add_ln700_7_fu_517_p2 <= std_logic_vector(unsigned(zext_ln700_6_fu_509_p1) + unsigned(cics_sums_V_0));
    add_ln700_8_fu_721_p2 <= std_logic_vector(unsigned(zext_ln700_7_fu_717_p1) + unsigned(zext_ln700_2_fu_318_p1));
    add_ln700_9_fu_663_p2 <= std_logic_vector(unsigned(zext_ln700_8_fu_659_p1) + unsigned(zext_ln700_2_fu_318_p1));
    add_ln700_fu_1126_p2 <= std_logic_vector(unsigned(zext_ln700_fu_298_p1) + unsigned(cics_sums_V_0));
    add_ln701_fu_1351_p2 <= std_logic_vector(signed(ap_const_lv17_1FFF8) + signed(icmpChecksum_V));
    and_ln91_1_fu_1054_p2 <= (icmp_ln879_fu_1030_p2 and and_ln91_fu_1048_p2);
    and_ln91_fu_1048_p2 <= (icmp_ln879_2_fu_1042_p2 and icmp_ln879_1_fu_1036_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, s_axis_TVALID, ap_predicate_op18_read_state1, packageBuffer1_V_full_n, cics_writeLastOne_lo_reg_1400, ap_predicate_op212_write_state2, ap_predicate_op218_write_state2, ap_predicate_op228_write_state2, validFifo_V_full_n, ap_predicate_op235_write_state2, ap_predicate_op237_write_state2, checksumStreams_V_V_s_full_n, ap_predicate_op239_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((s_axis_TVALID = ap_const_logic_0) and (ap_predicate_op18_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op237_write_state2 = ap_const_boolean_1)) or ((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op235_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op212_write_state2 = ap_const_boolean_1)) or ((cics_writeLastOne_lo_reg_1400 = ap_const_lv1_1) and (packageBuffer1_V_full_n = ap_const_logic_0)) or ((checksumStreams_V_V_s_full_n = ap_const_logic_0) and (ap_predicate_op239_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, s_axis_TVALID, ap_predicate_op18_read_state1, packageBuffer1_V_full_n, cics_writeLastOne_lo_reg_1400, ap_predicate_op212_write_state2, ap_predicate_op218_write_state2, ap_predicate_op228_write_state2, validFifo_V_full_n, ap_predicate_op235_write_state2, ap_predicate_op237_write_state2, checksumStreams_V_V_s_full_n, ap_predicate_op239_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((s_axis_TVALID = ap_const_logic_0) and (ap_predicate_op18_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op237_write_state2 = ap_const_boolean_1)) or ((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op235_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op212_write_state2 = ap_const_boolean_1)) or ((cics_writeLastOne_lo_reg_1400 = ap_const_lv1_1) and (packageBuffer1_V_full_n = ap_const_logic_0)) or ((checksumStreams_V_V_s_full_n = ap_const_logic_0) and (ap_predicate_op239_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, s_axis_TVALID, ap_predicate_op18_read_state1, packageBuffer1_V_full_n, cics_writeLastOne_lo_reg_1400, ap_predicate_op212_write_state2, ap_predicate_op218_write_state2, ap_predicate_op228_write_state2, validFifo_V_full_n, ap_predicate_op235_write_state2, ap_predicate_op237_write_state2, checksumStreams_V_V_s_full_n, ap_predicate_op239_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((s_axis_TVALID = ap_const_logic_0) and (ap_predicate_op18_read_state1 = ap_const_boolean_1)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op237_write_state2 = ap_const_boolean_1)) or ((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op235_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op212_write_state2 = ap_const_boolean_1)) or ((cics_writeLastOne_lo_reg_1400 = ap_const_lv1_1) and (packageBuffer1_V_full_n = ap_const_logic_0)) or ((checksumStreams_V_V_s_full_n = ap_const_logic_0) and (ap_predicate_op239_write_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, s_axis_TVALID, ap_predicate_op18_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((s_axis_TVALID = ap_const_logic_0) and (ap_predicate_op18_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(packageBuffer1_V_full_n, cics_writeLastOne_lo_reg_1400, ap_predicate_op212_write_state2, ap_predicate_op218_write_state2, ap_predicate_op228_write_state2, validFifo_V_full_n, ap_predicate_op235_write_state2, ap_predicate_op237_write_state2, checksumStreams_V_V_s_full_n, ap_predicate_op239_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op237_write_state2 = ap_const_boolean_1)) or ((validFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op235_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op218_write_state2 = ap_const_boolean_1)) or ((packageBuffer1_V_full_n = ap_const_logic_0) and (ap_predicate_op212_write_state2 = ap_const_boolean_1)) or ((cics_writeLastOne_lo_reg_1400 = ap_const_lv1_1) and (packageBuffer1_V_full_n = ap_const_logic_0)) or ((checksumStreams_V_V_s_full_n = ap_const_logic_0) and (ap_predicate_op239_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_1009_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, cics_writeLastOne)
    begin
                ap_condition_1009 <= ((cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_1011_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_computeCs, tmp_last_V_17_fu_343_p1)
    begin
                ap_condition_1011 <= ((tmp_last_V_17_fu_343_p1 = ap_const_lv1_1) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0));
    end process;


    ap_condition_1017_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_computeCs, t_V_1_load_fu_351_p1)
    begin
                ap_condition_1017 <= ((t_V_1_load_fu_351_p1 = ap_const_lv16_0) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0));
    end process;


    ap_condition_1024_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_computeCs, trunc_ln321_fu_347_p1, t_V_1_load_fu_351_p1, icmp_ln879_3_fu_491_p2)
    begin
                ap_condition_1024 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (trunc_ln321_fu_347_p1 = ap_const_lv1_1) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (icmp_ln879_3_fu_491_p2 = ap_const_lv1_0));
    end process;


    ap_condition_1027_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_computeCs, t_V_1_load_fu_351_p1, icmp_ln879_3_fu_491_p2)
    begin
                ap_condition_1027 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (icmp_ln879_3_fu_491_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0));
    end process;


    ap_condition_1034_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_computeCs, t_V_1_load_fu_351_p1, icmp_ln879_4_fu_637_p2, tmp_33_fu_643_p3)
    begin
                ap_condition_1034 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (tmp_33_fu_643_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (icmp_ln879_4_fu_637_p2 = ap_const_lv1_0));
    end process;


    ap_condition_1037_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_computeCs, t_V_1_load_fu_351_p1, icmp_ln879_4_fu_637_p2)
    begin
                ap_condition_1037 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (icmp_ln879_4_fu_637_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0));
    end process;


    ap_condition_1043_assign_proc : process(t_V_1_load_fu_351_p1, icmp_ln879_5_fu_767_p2, tmp_36_fu_773_p3)
    begin
                ap_condition_1043 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (tmp_36_fu_773_p3 = ap_const_lv1_1) and (icmp_ln879_5_fu_767_p2 = ap_const_lv1_0));
    end process;


    ap_condition_1046_assign_proc : process(t_V_1_load_fu_351_p1, icmp_ln879_5_fu_767_p2)
    begin
                ap_condition_1046 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (icmp_ln879_5_fu_767_p2 = ap_const_lv1_1));
    end process;


    ap_condition_1052_assign_proc : process(t_V_1_load_fu_351_p1, icmp_ln879_6_fu_887_p2, tmp_39_fu_893_p3)
    begin
                ap_condition_1052 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (tmp_39_fu_893_p3 = ap_const_lv1_1) and (icmp_ln879_6_fu_887_p2 = ap_const_lv1_0));
    end process;


    ap_condition_1055_assign_proc : process(t_V_1_load_fu_351_p1, icmp_ln879_6_fu_887_p2)
    begin
                ap_condition_1055 <= (not((t_V_1_load_fu_351_p1 = ap_const_lv16_2)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_1)) and not((t_V_1_load_fu_351_p1 = ap_const_lv16_0)) and (icmp_ln879_6_fu_887_p2 = ap_const_lv1_1));
    end process;


    ap_condition_137_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_137 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_249_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_writeLastOne, cics_computeCs, tmp_last_V_17_fu_343_p1)
    begin
                ap_condition_249 <= ((tmp_last_V_17_fu_343_p1 = ap_const_lv1_1) and (tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0));
    end process;


    ap_condition_371_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_162_p5, ap_block_pp0_stage0_11001, cics_writeLastOne, cics_computeCs)
    begin
                ap_condition_371 <= ((tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_373_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_162_p5, cics_writeLastOne, cics_computeCs, ap_block_pp0_stage0)
    begin
                ap_condition_373 <= ((tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_384_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_384 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4_assign_proc : process(tmp_last_V_17_fu_343_p1, ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207, add_ln700_14_fu_997_p2, ap_condition_373)
    begin
        if ((ap_const_boolean_1 = ap_condition_373)) then
            if ((tmp_last_V_17_fu_343_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 <= add_ln700_14_fu_997_p2;
            elsif ((tmp_last_V_17_fu_343_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 <= ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207;
            end if;
        else 
            ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 <= ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207;
        end if; 
    end process;


    ap_phi_mux_empty_52_phi_fu_220_p8_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, cics_writeLastOne_lo_reg_1400, cics_computeCs_load_reg_1404, tmp_reg_1408, t_V_1_reg_1436, ap_block_pp0_stage0, p_Result_10_fu_1296_p5, ap_phi_reg_pp0_iter1_empty_52_reg_217)
    begin
        if (((t_V_1_reg_1436 = ap_const_lv16_2) and (tmp_reg_1408 = ap_const_lv1_1) and (cics_computeCs_load_reg_1404 = ap_const_lv1_0) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_empty_52_phi_fu_220_p8 <= p_Result_10_fu_1296_p5;
        else 
            ap_phi_mux_empty_52_phi_fu_220_p8 <= ap_phi_reg_pp0_iter1_empty_52_reg_217;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_empty_52_reg_217 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op18_read_state1_assign_proc : process(tmp_nbreadreq_fu_162_p5, cics_writeLastOne, cics_computeCs)
    begin
                ap_predicate_op18_read_state1 <= ((tmp_nbreadreq_fu_162_p5 = ap_const_lv1_1) and (cics_computeCs = ap_const_lv1_0) and (cics_writeLastOne = ap_const_lv1_0));
    end process;


    ap_predicate_op212_write_state2_assign_proc : process(cics_writeLastOne_lo_reg_1400, cics_computeCs_load_reg_1404, tmp_reg_1408, t_V_1_reg_1436)
    begin
                ap_predicate_op212_write_state2 <= ((t_V_1_reg_1436 = ap_const_lv16_2) and (tmp_reg_1408 = ap_const_lv1_1) and (cics_computeCs_load_reg_1404 = ap_const_lv1_0) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0));
    end process;


    ap_predicate_op218_write_state2_assign_proc : process(cics_writeLastOne_lo_reg_1400, cics_computeCs_load_reg_1404, tmp_reg_1408, t_V_1_reg_1436)
    begin
                ap_predicate_op218_write_state2 <= ((t_V_1_reg_1436 = ap_const_lv16_1) and (tmp_reg_1408 = ap_const_lv1_1) and (cics_computeCs_load_reg_1404 = ap_const_lv1_0) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0));
    end process;


    ap_predicate_op228_write_state2_assign_proc : process(cics_writeLastOne_lo_reg_1400, cics_computeCs_load_reg_1404, tmp_reg_1408, t_V_1_reg_1436)
    begin
                ap_predicate_op228_write_state2 <= (not((t_V_1_reg_1436 = ap_const_lv16_0)) and not((t_V_1_reg_1436 = ap_const_lv16_1)) and not((t_V_1_reg_1436 = ap_const_lv16_2)) and (tmp_reg_1408 = ap_const_lv1_1) and (cics_computeCs_load_reg_1404 = ap_const_lv1_0) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0));
    end process;


    ap_predicate_op235_write_state2_assign_proc : process(cics_writeLastOne_lo_reg_1400, cics_computeCs_load_reg_1404, t_V_reg_1468, and_ln91_1_reg_1472)
    begin
                ap_predicate_op235_write_state2 <= ((t_V_reg_1468 = ap_const_lv2_3) and (cics_computeCs_load_reg_1404 = ap_const_lv1_1) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln91_1_reg_1472));
    end process;


    ap_predicate_op237_write_state2_assign_proc : process(cics_writeLastOne_lo_reg_1400, cics_computeCs_load_reg_1404, t_V_reg_1468, and_ln91_1_reg_1472)
    begin
                ap_predicate_op237_write_state2 <= ((t_V_reg_1468 = ap_const_lv2_3) and (cics_computeCs_load_reg_1404 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln91_1_reg_1472) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0));
    end process;


    ap_predicate_op239_write_state2_assign_proc : process(cics_writeLastOne_lo_reg_1400, cics_computeCs_load_reg_1404, t_V_reg_1468, and_ln91_1_reg_1472)
    begin
                ap_predicate_op239_write_state2 <= ((t_V_reg_1468 = ap_const_lv2_3) and (cics_computeCs_load_reg_1404 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln91_1_reg_1472) and (cics_writeLastOne_lo_reg_1400 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    checksumStreams_V_V_s_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, checksumStreams_V_V_s_full_n, ap_predicate_op239_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op239_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            checksumStreams_V_V_s_blk_n <= checksumStreams_V_V_s_full_n;
        else 
            checksumStreams_V_V_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    checksumStreams_V_V_s_din <= icmpChecksum_V(16 - 1 downto 0);

    checksumStreams_V_V_s_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op239_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op239_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            checksumStreams_V_V_s_write <= ap_const_logic_1;
        else 
            checksumStreams_V_V_s_write <= ap_const_logic_0;
        end if; 
    end process;

    cics_computeCs_load_load_fu_290_p1 <= cics_computeCs;
    cics_writeLastOne_lo_load_fu_286_p1 <= cics_writeLastOne;
    grp_fu_230_p4 <= s_axis_TDATA(39 downto 32);
    grp_fu_239_p4 <= s_axis_TDATA(47 downto 40);
    grp_fu_248_p4 <= s_axis_TDATA(63 downto 56);
    grp_fu_257_p4 <= s_axis_TDATA(55 downto 48);
    grp_fu_266_p4 <= s_axis_TDATA(23 downto 16);
    grp_fu_275_p2 <= (icmpChecksum_V xor ap_const_lv17_1FFFF);
    icmp_ln879_1_fu_1036_p2 <= "1" when (icmpType_V = ap_const_lv8_8) else "0";
    icmp_ln879_2_fu_1042_p2 <= "1" when (icmpCode_V = ap_const_lv8_0) else "0";
    icmp_ln879_3_fu_491_p2 <= "1" when (trunc_ln647_5_fu_487_p1 = ap_const_lv2_3) else "0";
    icmp_ln879_4_fu_637_p2 <= "1" when (p_Result_127_1_i_fu_627_p4 = ap_const_lv2_3) else "0";
    icmp_ln879_5_fu_767_p2 <= "1" when (p_Result_127_2_i_fu_757_p4 = ap_const_lv2_3) else "0";
    icmp_ln879_6_fu_887_p2 <= "1" when (p_Result_127_3_i_fu_877_p4 = ap_const_lv2_3) else "0";
    icmp_ln879_fu_1030_p2 <= "1" when (trunc_ln647_fu_1026_p1 = ap_const_lv16_0) else "0";
    p_Result_10_fu_1296_p5 <= (tmp_data_V_26_reg_1412(63 downto 40) & tmp_23_i_fu_1288_p3);
    p_Result_123_1_i_fu_415_p3 <= (grp_fu_257_p4 & grp_fu_248_p4);
    p_Result_123_i_fu_367_p3 <= (grp_fu_230_p4 & grp_fu_239_p4);
    p_Result_127_1_i_fu_627_p4 <= s_axis_TKEEP(3 downto 2);
    p_Result_127_2_i_fu_757_p4 <= s_axis_TKEEP(5 downto 4);
    p_Result_127_3_i_fu_877_p4 <= s_axis_TKEEP(7 downto 6);
    p_Result_128_1_i_fu_699_p4 <= s_axis_TDATA(31 downto 24);
    p_Result_128_i_fu_557_p4 <= s_axis_TDATA(15 downto 8);
    p_Result_131_1_i_fu_709_p3 <= (grp_fu_266_p4 & p_Result_128_1_i_fu_699_p4);
    p_Result_131_2_i_fu_829_p3 <= (grp_fu_230_p4 & grp_fu_239_p4);
    p_Result_131_3_i_fu_949_p3 <= (grp_fu_257_p4 & grp_fu_248_p4);
    p_Result_131_i_fu_571_p3 <= (trunc_ln647_8_fu_567_p1 & p_Result_128_i_fu_557_p4);
    p_Result_134_1_i_fu_651_p3 <= (grp_fu_266_p4 & ap_const_lv8_0);
    p_Result_134_2_i_fu_781_p3 <= (grp_fu_230_p4 & ap_const_lv8_0);
    p_Result_134_3_i_fu_901_p3 <= (grp_fu_257_p4 & ap_const_lv8_0);
    p_Result_134_i_fu_501_p3 <= (trunc_ln647_9_fu_497_p1 & ap_const_lv8_0);
    p_Result_27_i_fu_1244_p4 <= tmp_data_V_26_reg_1412(63 downto 48);
    p_Result_29_i_fu_1278_p4 <= cics_prevWord_data_V(63 downto 32);
    p_Result_s_fu_1253_p3 <= (ap_const_lv1_1 & p_Result_27_i_fu_1244_p4);

    packageBuffer1_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, packageBuffer1_V_full_n, cics_writeLastOne_lo_reg_1400, ap_predicate_op212_write_state2, ap_predicate_op218_write_state2, ap_predicate_op228_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op228_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op218_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op212_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((cics_writeLastOne_lo_reg_1400 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            packageBuffer1_V_blk_n <= packageBuffer1_V_full_n;
        else 
            packageBuffer1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    packageBuffer1_V_din_assign_proc : process(cics_writeLastOne_lo_reg_1400, ap_predicate_op212_write_state2, ap_predicate_op218_write_state2, ap_predicate_op228_write_state2, tmp_2_fu_1267_p4, tmp_1_fu_1308_p4, tmp_3_fu_1319_p4, tmp12_fu_1389_p4, ap_condition_384)
    begin
        if ((ap_const_boolean_1 = ap_condition_384)) then
            if ((cics_writeLastOne_lo_reg_1400 = ap_const_lv1_1)) then 
                packageBuffer1_V_din <= tmp12_fu_1389_p4;
            elsif ((ap_predicate_op228_write_state2 = ap_const_boolean_1)) then 
                packageBuffer1_V_din <= tmp_3_fu_1319_p4;
            elsif ((ap_predicate_op218_write_state2 = ap_const_boolean_1)) then 
                packageBuffer1_V_din <= tmp_1_fu_1308_p4;
            elsif ((ap_predicate_op212_write_state2 = ap_const_boolean_1)) then 
                packageBuffer1_V_din <= tmp_2_fu_1267_p4;
            else 
                packageBuffer1_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            packageBuffer1_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    packageBuffer1_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, cics_writeLastOne_lo_reg_1400, ap_predicate_op212_write_state2, ap_predicate_op218_write_state2, ap_predicate_op228_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op228_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op218_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op212_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((cics_writeLastOne_lo_reg_1400 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            packageBuffer1_V_write <= ap_const_logic_1;
        else 
            packageBuffer1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    r_V_3_fu_1066_p2 <= (cics_sums_V_0 xor ap_const_lv17_1FFFF);

    s_axis_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, s_axis_TVALID, ap_predicate_op18_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op18_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            s_axis_TDATA_blk_n <= s_axis_TVALID;
        else 
            s_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_TREADY_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op18_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op18_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            s_axis_TREADY <= ap_const_logic_1;
        else 
            s_axis_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln214_fu_1373_p2 <= std_logic_vector(unsigned(trunc_ln214_fu_1365_p1) - unsigned(zext_ln214_20_fu_1369_p1));
    t_V_1_load_fu_351_p1 <= cics_wordCount_V;
    t_V_load_fu_1022_p1 <= cics_state_V;
    tmp12_fu_1389_p4 <= ((cics_prevWord_last_V & cics_prevWord_keep_V) & cics_prevWord_data_V);
    tmp_1_fu_1308_p4 <= ((cics_prevWord_last_V & cics_prevWord_keep_V) & cics_prevWord_data_V);
    tmp_23_i_fu_1288_p3 <= (ap_const_lv8_0 & p_Result_29_i_fu_1278_p4);
    tmp_24_fu_1132_p3 <= add_ln700_fu_1126_p2(16 downto 16);
    tmp_25_fu_1172_p3 <= add_ln700_1_fu_1166_p2(16 downto 16);
    tmp_26_fu_1088_p3 <= add_ln700_2_fu_1082_p2(16 downto 16);
    tmp_27_fu_1357_p3 <= add_ln701_fu_1351_p2(16 downto 16);
    tmp_28_fu_385_p3 <= add_ln700_3_fu_379_p2(16 downto 16);
    tmp_29_fu_433_p3 <= add_ln700_4_fu_427_p2(16 downto 16);
    tmp_2_fu_1267_p4 <= ((ap_const_lv9_FF & trunc_ln647_7_fu_1241_p1) & trunc_ln647_6_fu_1237_p1);
    tmp_30_fu_593_p3 <= add_ln700_5_fu_587_p2(16 downto 16);
    tmp_31_fu_523_p3 <= add_ln700_7_fu_517_p2(16 downto 16);
    tmp_32_fu_727_p3 <= add_ln700_8_fu_721_p2(16 downto 16);
    tmp_33_fu_643_p3 <= s_axis_TKEEP(2 downto 2);
    tmp_34_fu_669_p3 <= add_ln700_9_fu_663_p2(16 downto 16);
    tmp_35_fu_847_p3 <= add_ln700_10_fu_841_p2(16 downto 16);
    tmp_36_fu_773_p3 <= s_axis_TKEEP(4 downto 4);
    tmp_37_fu_799_p3 <= add_ln700_11_fu_793_p2(16 downto 16);
    tmp_38_fu_967_p3 <= add_ln700_12_fu_961_p2(16 downto 16);
    tmp_39_fu_893_p3 <= s_axis_TKEEP(6 downto 6);
    tmp_3_fu_1319_p4 <= ((cics_prevWord_last_V & cics_prevWord_keep_V) & cics_prevWord_data_V);
    tmp_40_fu_919_p3 <= add_ln700_13_fu_913_p2(16 downto 16);
    tmp_last_V_17_fu_343_p1 <= s_axis_TLAST;
    tmp_nbreadreq_fu_162_p5 <= (0=>(s_axis_TVALID), others=>'-');
    trunc_ln214_fu_1365_p1 <= add_ln701_fu_1351_p2(16 - 1 downto 0);
    trunc_ln321_fu_347_p1 <= s_axis_TKEEP(1 - 1 downto 0);
    trunc_ln647_5_fu_487_p1 <= s_axis_TKEEP(2 - 1 downto 0);
    trunc_ln647_6_fu_1237_p1 <= cics_prevWord_data_V(32 - 1 downto 0);
    trunc_ln647_7_fu_1241_p1 <= tmp_data_V_26_reg_1412(32 - 1 downto 0);
    trunc_ln647_8_fu_567_p1 <= s_axis_TDATA(8 - 1 downto 0);
    trunc_ln647_9_fu_497_p1 <= s_axis_TDATA(8 - 1 downto 0);
    trunc_ln647_fu_1026_p1 <= cics_sums_V_0(16 - 1 downto 0);
    trunc_ln700_1_fu_1078_p1 <= cics_sums_V_0(16 - 1 downto 0);
    trunc_ln700_2_fu_583_p1 <= cics_sums_V_0(16 - 1 downto 0);
    trunc_ln700_3_fu_513_p1 <= cics_sums_V_0(16 - 1 downto 0);
    trunc_ln700_fu_1122_p1 <= cics_sums_V_0(16 - 1 downto 0);

    validFifo_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, validFifo_V_full_n, ap_predicate_op235_write_state2, ap_predicate_op237_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op237_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op235_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            validFifo_V_blk_n <= validFifo_V_full_n;
        else 
            validFifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    validFifo_V_din_assign_proc : process(ap_predicate_op235_write_state2, ap_predicate_op237_write_state2, ap_condition_384)
    begin
        if ((ap_const_boolean_1 = ap_condition_384)) then
            if ((ap_predicate_op237_write_state2 = ap_const_boolean_1)) then 
                validFifo_V_din <= ap_const_lv1_1;
            elsif ((ap_predicate_op235_write_state2 = ap_const_boolean_1)) then 
                validFifo_V_din <= ap_const_lv1_0;
            else 
                validFifo_V_din <= "X";
            end if;
        else 
            validFifo_V_din <= "X";
        end if; 
    end process;


    validFifo_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op235_write_state2, ap_predicate_op237_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op237_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op235_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            validFifo_V_write <= ap_const_logic_1;
        else 
            validFifo_V_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln214_10_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_28_fu_385_p3),16));
    zext_ln214_11_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_29_fu_433_p3),16));
    zext_ln214_12_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_30_fu_593_p3),16));
    zext_ln214_13_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_31_fu_523_p3),16));
    zext_ln214_14_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_727_p3),16));
    zext_ln214_15_fu_677_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_fu_669_p3),16));
    zext_ln214_16_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_fu_847_p3),16));
    zext_ln214_17_fu_807_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_37_fu_799_p3),16));
    zext_ln214_18_fu_975_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_fu_967_p3),16));
    zext_ln214_19_fu_927_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_40_fu_919_p3),16));
    zext_ln214_20_fu_1369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_27_fu_1357_p3),16));
    zext_ln214_3_fu_1112_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln214_7_fu_1106_p2),17));
    zext_ln214_4_fu_1379_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln214_fu_1373_p2),17));
    zext_ln214_5_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln214_13_fu_611_p2),17));
    zext_ln214_6_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln214_15_fu_541_p2),17));
    zext_ln214_7_fu_1140_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_1132_p3),16));
    zext_ln214_8_fu_1180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_1172_p3),16));
    zext_ln214_9_fu_1096_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_1088_p3),16));
    zext_ln214_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln214_3_fu_1150_p2),17));
    zext_ln700_10_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_134_2_i_fu_781_p3),17));
    zext_ln700_11_fu_957_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_131_3_i_fu_949_p3),17));
    zext_ln700_12_fu_909_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_134_3_i_fu_901_p3),17));
    zext_ln700_1_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cics_sums_V_3),17));
    zext_ln700_2_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cics_sums_V_1),17));
    zext_ln700_3_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_123_i_fu_367_p3),17));
    zext_ln700_4_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_123_1_i_fu_415_p3),17));
    zext_ln700_5_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_131_i_fu_571_p3),17));
    zext_ln700_6_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_134_i_fu_501_p3),17));
    zext_ln700_7_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_131_1_i_fu_709_p3),17));
    zext_ln700_8_fu_659_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_134_1_i_fu_651_p3),17));
    zext_ln700_9_fu_837_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_131_2_i_fu_829_p3),17));
    zext_ln700_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cics_sums_V_2),17));
end behav;
