-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dropper is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    packageBuffer1_V_dout : IN STD_LOGIC_VECTOR (72 downto 0);
    packageBuffer1_V_empty_n : IN STD_LOGIC;
    packageBuffer1_V_read : OUT STD_LOGIC;
    validFifo_V_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    validFifo_V_empty_n : IN STD_LOGIC;
    validFifo_V_read : OUT STD_LOGIC;
    dataStreams_V_data_V_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    dataStreams_V_data_V_full_n : IN STD_LOGIC;
    dataStreams_V_data_V_write : OUT STD_LOGIC;
    dataStreams_V_keep_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dataStreams_V_keep_V_full_n : IN STD_LOGIC;
    dataStreams_V_keep_V_write : OUT STD_LOGIC;
    dataStreams_V_last_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    dataStreams_V_last_V_full_n : IN STD_LOGIC;
    dataStreams_V_last_V_write : OUT STD_LOGIC );
end;


architecture behav of dropper is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal d_isFirstWord : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal d_drop : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal packageBuffer1_V_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_54_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_nbreadreq_fu_81_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal validFifo_V_blk_n : STD_LOGIC;
    signal dataStreams_V_data_V_blk_n : STD_LOGIC;
    signal tmp_23_read_fu_89_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal d_drop_load_load_fu_179_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal dataStreams_V_keep_V_blk_n : STD_LOGIC;
    signal dataStreams_V_last_V_blk_n : STD_LOGIC;
    signal ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op12_read_state1 : BOOLEAN;
    signal io_acc_block_signal_op17 : STD_LOGIC;
    signal ap_predicate_op17_write_state1 : BOOLEAN;
    signal ap_predicate_op23_read_state1 : BOOLEAN;
    signal ap_predicate_op27_read_state1 : BOOLEAN;
    signal io_acc_block_signal_op29 : STD_LOGIC;
    signal ap_predicate_op29_write_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_162_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln347_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln347_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln347_1_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_fu_183_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_data_V_24_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_112 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (or_ln347_1_fu_199_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                d_drop <= xor_ln347_fu_205_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (or_ln347_fu_193_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                d_isFirstWord <= packageBuffer1_V_dout(72 downto 72);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)));
    end process;


    ap_condition_112_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
                ap_condition_112 <= (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10_assign_proc : process(ap_CS_fsm_state1, d_isFirstWord, d_drop, validFifo_V_dout, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3, tmp_23_read_fu_89_p2, d_drop_load_load_fu_179_p1)
    begin
        if (((tmp_23_read_fu_89_p2 = ap_const_lv1_0) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10 <= ap_const_lv1_1;
        elsif ((((d_drop = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((d_isFirstWord = ap_const_lv1_0) and (d_drop_load_load_fu_179_p1 = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((validFifo_V_dout = ap_const_lv1_1) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10 <= ap_const_lv1_0;
        else 
            ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10 <= "X";
        end if; 
    end process;


    ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10_assign_proc : process(ap_CS_fsm_state1, d_isFirstWord, d_drop, validFifo_V_dout, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3, tmp_23_read_fu_89_p2, d_drop_load_load_fu_179_p1)
    begin
        if ((((validFifo_V_dout = ap_const_lv1_1) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_23_read_fu_89_p2 = ap_const_lv1_0) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10 <= ap_const_lv1_1;
        elsif ((((d_drop = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((d_isFirstWord = ap_const_lv1_0) and (d_drop_load_load_fu_179_p1 = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10 <= ap_const_lv1_0;
        else 
            ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10 <= "X";
        end if; 
    end process;


    ap_predicate_op12_read_state1_assign_proc : process(d_isFirstWord, tmp_nbreadreq_fu_54_p3)
    begin
                ap_predicate_op12_read_state1 <= ((d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op17_write_state1_assign_proc : process(d_isFirstWord, d_drop, tmp_nbreadreq_fu_54_p3)
    begin
                ap_predicate_op17_write_state1 <= ((d_drop = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op23_read_state1_assign_proc : process(d_isFirstWord, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
                ap_predicate_op23_read_state1 <= ((tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op27_read_state1_assign_proc : process(d_isFirstWord, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
                ap_predicate_op27_read_state1 <= ((tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1));
    end process;


    ap_predicate_op29_write_state1_assign_proc : process(d_isFirstWord, validFifo_V_dout, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
                ap_predicate_op29_write_state1 <= ((validFifo_V_dout = ap_const_lv1_1) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    d_drop_load_load_fu_179_p1 <= d_drop;

    dataStreams_V_data_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, d_isFirstWord, d_drop, validFifo_V_dout, dataStreams_V_data_V_full_n, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (d_drop = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (validFifo_V_dout = ap_const_lv1_1) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            dataStreams_V_data_V_blk_n <= dataStreams_V_data_V_full_n;
        else 
            dataStreams_V_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dataStreams_V_data_V_din_assign_proc : process(ap_predicate_op17_write_state1, ap_predicate_op29_write_state1, tmp_data_V_fu_183_p1, tmp_data_V_24_fu_188_p1, ap_condition_112)
    begin
        if ((ap_const_boolean_1 = ap_condition_112)) then
            if ((ap_predicate_op29_write_state1 = ap_const_boolean_1)) then 
                dataStreams_V_data_V_din <= tmp_data_V_24_fu_188_p1;
            elsif ((ap_predicate_op17_write_state1 = ap_const_boolean_1)) then 
                dataStreams_V_data_V_din <= tmp_data_V_fu_183_p1;
            else 
                dataStreams_V_data_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            dataStreams_V_data_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dataStreams_V_data_V_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) then 
            dataStreams_V_data_V_write <= ap_const_logic_1;
        else 
            dataStreams_V_data_V_write <= ap_const_logic_0;
        end if; 
    end process;


    dataStreams_V_keep_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, d_isFirstWord, d_drop, validFifo_V_dout, dataStreams_V_keep_V_full_n, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (d_drop = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (validFifo_V_dout = ap_const_lv1_1) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            dataStreams_V_keep_V_blk_n <= dataStreams_V_keep_V_full_n;
        else 
            dataStreams_V_keep_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dataStreams_V_keep_V_din <= packageBuffer1_V_dout(71 downto 64);

    dataStreams_V_keep_V_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) then 
            dataStreams_V_keep_V_write <= ap_const_logic_1;
        else 
            dataStreams_V_keep_V_write <= ap_const_logic_0;
        end if; 
    end process;


    dataStreams_V_last_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, d_isFirstWord, d_drop, validFifo_V_dout, dataStreams_V_last_V_full_n, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (d_drop = ap_const_lv1_0) and (d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (validFifo_V_dout = ap_const_lv1_1) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            dataStreams_V_last_V_blk_n <= dataStreams_V_last_V_full_n;
        else 
            dataStreams_V_last_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dataStreams_V_last_V_din <= packageBuffer1_V_dout(72 downto 72);

    dataStreams_V_last_V_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) then 
            dataStreams_V_last_V_write <= ap_const_logic_1;
        else 
            dataStreams_V_last_V_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_162_p3 <= packageBuffer1_V_dout(72 downto 72);
    io_acc_block_signal_op17 <= (dataStreams_V_last_V_full_n and dataStreams_V_keep_V_full_n and dataStreams_V_data_V_full_n);
    io_acc_block_signal_op29 <= (dataStreams_V_last_V_full_n and dataStreams_V_keep_V_full_n and dataStreams_V_data_V_full_n);
    or_ln347_1_fu_199_p2 <= (grp_fu_162_p3 or ap_phi_mux_d_drop_flag_1_i_phi_fu_118_p10);
    or_ln347_fu_193_p2 <= (grp_fu_162_p3 or ap_phi_mux_d_isFirstWord_flag_0_phi_fu_98_p10);

    packageBuffer1_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, d_isFirstWord, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (d_isFirstWord = ap_const_lv1_0) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            packageBuffer1_V_blk_n <= packageBuffer1_V_empty_n;
        else 
            packageBuffer1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    packageBuffer1_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)))) then 
            packageBuffer1_V_read <= ap_const_logic_1;
        else 
            packageBuffer1_V_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_18_nbreadreq_fu_81_p3 <= (0=>(validFifo_V_empty_n), others=>'-');
    tmp_23_read_fu_89_p2 <= validFifo_V_dout;
    tmp_data_V_24_fu_188_p1 <= packageBuffer1_V_dout(64 - 1 downto 0);
    tmp_data_V_fu_183_p1 <= packageBuffer1_V_dout(64 - 1 downto 0);
    tmp_nbreadreq_fu_54_p3 <= (0=>(packageBuffer1_V_empty_n), others=>'-');

    validFifo_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, d_isFirstWord, validFifo_V_empty_n, tmp_nbreadreq_fu_54_p3, tmp_18_nbreadreq_fu_81_p3)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_18_nbreadreq_fu_81_p3 = ap_const_lv1_1) and (d_isFirstWord = ap_const_lv1_1) and (tmp_nbreadreq_fu_54_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            validFifo_V_blk_n <= validFifo_V_empty_n;
        else 
            validFifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    validFifo_V_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, packageBuffer1_V_empty_n, validFifo_V_empty_n, ap_predicate_op12_read_state1, io_acc_block_signal_op17, ap_predicate_op17_write_state1, ap_predicate_op23_read_state1, ap_predicate_op27_read_state1, io_acc_block_signal_op29, ap_predicate_op29_write_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((validFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op27_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op17 = ap_const_logic_0) and (ap_predicate_op17_write_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state1 = ap_const_boolean_1)) or ((packageBuffer1_V_empty_n = ap_const_logic_0) and (ap_predicate_op12_read_state1 = ap_const_boolean_1)) or ((io_acc_block_signal_op29 = ap_const_logic_0) and (ap_predicate_op29_write_state1 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_predicate_op27_read_state1 = ap_const_boolean_1))) then 
            validFifo_V_read <= ap_const_logic_1;
        else 
            validFifo_V_read <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln347_fu_205_p2 <= (grp_fu_162_p3 xor ap_const_lv1_1);
end behav;
