// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rshiftWordByOctet (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rx_udp2shiftFifo_V_d_dout,
        rx_udp2shiftFifo_V_d_empty_n,
        rx_udp2shiftFifo_V_d_read,
        rx_udp2shiftFifo_V_k_dout,
        rx_udp2shiftFifo_V_k_empty_n,
        rx_udp2shiftFifo_V_k_read,
        rx_udp2shiftFifo_V_l_dout,
        rx_udp2shiftFifo_V_l_empty_n,
        rx_udp2shiftFifo_V_l_read,
        m_axis_rx_data_TREADY,
        m_axis_rx_data_TDATA,
        m_axis_rx_data_TVALID,
        m_axis_rx_data_TKEEP,
        m_axis_rx_data_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] rx_udp2shiftFifo_V_d_dout;
input   rx_udp2shiftFifo_V_d_empty_n;
output   rx_udp2shiftFifo_V_d_read;
input  [7:0] rx_udp2shiftFifo_V_k_dout;
input   rx_udp2shiftFifo_V_k_empty_n;
output   rx_udp2shiftFifo_V_k_read;
input  [0:0] rx_udp2shiftFifo_V_l_dout;
input   rx_udp2shiftFifo_V_l_empty_n;
output   rx_udp2shiftFifo_V_l_read;
input   m_axis_rx_data_TREADY;
output  [63:0] m_axis_rx_data_TDATA;
output   m_axis_rx_data_TVALID;
output  [7:0] m_axis_rx_data_TKEEP;
output  [0:0] m_axis_rx_data_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rx_udp2shiftFifo_V_d_read;
reg rx_udp2shiftFifo_V_k_read;
reg rx_udp2shiftFifo_V_l_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    io_acc_block_signal_op6;
wire   [0:0] tmp_nbreadreq_fu_38_p5;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    output_V_data_V_1_ack_in;
reg   [0:0] tmp_reg_85;
reg    ap_block_state2_io;
wire    output_V_data_V_1_ack_out;
reg   [1:0] output_V_data_V_1_state;
wire    output_V_keep_V_1_ack_out;
reg   [1:0] output_V_keep_V_1_state;
wire    output_V_last_V_1_ack_out;
reg   [1:0] output_V_last_V_1_state;
reg    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] tmp_reg_85_pp0_iter1_reg;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
reg   [63:0] output_V_data_V_1_data_out;
reg    output_V_data_V_1_vld_in;
wire    output_V_data_V_1_vld_out;
reg   [63:0] output_V_data_V_1_payload_A;
reg   [63:0] output_V_data_V_1_payload_B;
reg    output_V_data_V_1_sel_rd;
reg    output_V_data_V_1_sel_wr;
wire    output_V_data_V_1_sel;
wire    output_V_data_V_1_load_A;
wire    output_V_data_V_1_load_B;
wire    output_V_data_V_1_state_cmp_full;
reg   [7:0] output_V_keep_V_1_data_out;
reg    output_V_keep_V_1_vld_in;
wire    output_V_keep_V_1_vld_out;
wire    output_V_keep_V_1_ack_in;
reg   [7:0] output_V_keep_V_1_payload_A;
reg   [7:0] output_V_keep_V_1_payload_B;
reg    output_V_keep_V_1_sel_rd;
reg    output_V_keep_V_1_sel_wr;
wire    output_V_keep_V_1_sel;
wire    output_V_keep_V_1_load_A;
wire    output_V_keep_V_1_load_B;
wire    output_V_keep_V_1_state_cmp_full;
reg   [0:0] output_V_last_V_1_data_out;
reg    output_V_last_V_1_vld_in;
wire    output_V_last_V_1_vld_out;
wire    output_V_last_V_1_ack_in;
reg   [0:0] output_V_last_V_1_payload_A;
reg   [0:0] output_V_last_V_1_payload_B;
reg    output_V_last_V_1_sel_rd;
reg    output_V_last_V_1_sel_wr;
wire    output_V_last_V_1_sel;
wire    output_V_last_V_1_load_A;
wire    output_V_last_V_1_load_B;
wire    output_V_last_V_1_state_cmp_full;
reg    m_axis_rx_data_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    rx_udp2shiftFifo_V_d_blk_n;
reg    rx_udp2shiftFifo_V_k_blk_n;
reg    rx_udp2shiftFifo_V_l_blk_n;
reg   [63:0] tmp_data_V_reg_89;
reg   [7:0] tmp_keep_V_reg_94;
reg   [0:0] tmp_last_V_reg_99;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 output_V_data_V_1_state = 2'd0;
#0 output_V_keep_V_1_state = 2'd0;
#0 output_V_last_V_1_state = 2'd0;
#0 output_V_data_V_1_sel_rd = 1'b0;
#0 output_V_data_V_1_sel_wr = 1'b0;
#0 output_V_keep_V_1_sel_rd = 1'b0;
#0 output_V_keep_V_1_sel_wr = 1'b0;
#0 output_V_last_V_1_sel_rd = 1'b0;
#0 output_V_last_V_1_sel_wr = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_data_V_1_ack_out == 1'b1) & (output_V_data_V_1_vld_out == 1'b1))) begin
            output_V_data_V_1_sel_rd <= ~output_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_data_V_1_ack_in == 1'b1) & (output_V_data_V_1_vld_in == 1'b1))) begin
            output_V_data_V_1_sel_wr <= ~output_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_data_V_1_state == 2'd3) & (output_V_data_V_1_vld_in == 1'b0) & (output_V_data_V_1_ack_out == 1'b1)) | ((output_V_data_V_1_state == 2'd2) & (output_V_data_V_1_vld_in == 1'b0)))) begin
            output_V_data_V_1_state <= 2'd2;
        end else if ((((output_V_data_V_1_state == 2'd1) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0) & (output_V_data_V_1_vld_in == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd1;
        end else if ((((output_V_data_V_1_state == 2'd1) & (output_V_data_V_1_ack_out == 1'b1)) | (~((output_V_data_V_1_vld_in == 1'b0) & (output_V_data_V_1_ack_out == 1'b1)) & ~((m_axis_rx_data_TREADY == 1'b0) & (output_V_data_V_1_vld_in == 1'b1)) & (output_V_data_V_1_state == 2'd3)) | ((output_V_data_V_1_state == 2'd2) & (output_V_data_V_1_vld_in == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd3;
        end else begin
            output_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_keep_V_1_ack_out == 1'b1) & (output_V_keep_V_1_vld_out == 1'b1))) begin
            output_V_keep_V_1_sel_rd <= ~output_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_keep_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_keep_V_1_ack_in == 1'b1) & (output_V_keep_V_1_vld_in == 1'b1))) begin
            output_V_keep_V_1_sel_wr <= ~output_V_keep_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_keep_V_1_state == 2'd3) & (output_V_keep_V_1_vld_in == 1'b0) & (output_V_keep_V_1_ack_out == 1'b1)) | ((output_V_keep_V_1_state == 2'd2) & (output_V_keep_V_1_vld_in == 1'b0)))) begin
            output_V_keep_V_1_state <= 2'd2;
        end else if ((((output_V_keep_V_1_state == 2'd1) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0) & (output_V_keep_V_1_vld_in == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd1;
        end else if ((((output_V_keep_V_1_state == 2'd1) & (output_V_keep_V_1_ack_out == 1'b1)) | (~((output_V_keep_V_1_vld_in == 1'b0) & (output_V_keep_V_1_ack_out == 1'b1)) & ~((m_axis_rx_data_TREADY == 1'b0) & (output_V_keep_V_1_vld_in == 1'b1)) & (output_V_keep_V_1_state == 2'd3)) | ((output_V_keep_V_1_state == 2'd2) & (output_V_keep_V_1_vld_in == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd3;
        end else begin
            output_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_last_V_1_ack_out == 1'b1) & (output_V_last_V_1_vld_out == 1'b1))) begin
            output_V_last_V_1_sel_rd <= ~output_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_last_V_1_ack_in == 1'b1) & (output_V_last_V_1_vld_in == 1'b1))) begin
            output_V_last_V_1_sel_wr <= ~output_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_last_V_1_state == 2'd2) & (output_V_last_V_1_vld_in == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (output_V_last_V_1_vld_in == 1'b0) & (output_V_last_V_1_ack_out == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd2;
        end else if ((((output_V_last_V_1_state == 2'd1) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0) & (output_V_last_V_1_vld_in == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd1;
        end else if ((((output_V_last_V_1_state == 2'd2) & (output_V_last_V_1_vld_in == 1'b1)) | ((output_V_last_V_1_state == 2'd1) & (output_V_last_V_1_ack_out == 1'b1)) | (~((output_V_last_V_1_vld_in == 1'b0) & (output_V_last_V_1_ack_out == 1'b1)) & ~((m_axis_rx_data_TREADY == 1'b0) & (output_V_last_V_1_vld_in == 1'b1)) & (output_V_last_V_1_state == 2'd3)))) begin
            output_V_last_V_1_state <= 2'd3;
        end else begin
            output_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_data_V_1_load_A == 1'b1)) begin
        output_V_data_V_1_payload_A <= tmp_data_V_reg_89;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_data_V_1_load_B == 1'b1)) begin
        output_V_data_V_1_payload_B <= tmp_data_V_reg_89;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_keep_V_1_load_A == 1'b1)) begin
        output_V_keep_V_1_payload_A <= tmp_keep_V_reg_94;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_keep_V_1_load_B == 1'b1)) begin
        output_V_keep_V_1_payload_B <= tmp_keep_V_reg_94;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_last_V_1_load_A == 1'b1)) begin
        output_V_last_V_1_payload_A <= tmp_last_V_reg_99;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_last_V_1_load_B == 1'b1)) begin
        output_V_last_V_1_payload_B <= tmp_last_V_reg_99;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_38_p5 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_data_V_reg_89 <= rx_udp2shiftFifo_V_d_dout;
        tmp_keep_V_reg_94 <= rx_udp2shiftFifo_V_k_dout;
        tmp_last_V_reg_99 <= rx_udp2shiftFifo_V_l_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_85 <= tmp_nbreadreq_fu_38_p5;
        tmp_reg_85_pp0_iter1_reg <= tmp_reg_85;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_85 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_85_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        m_axis_rx_data_TDATA_blk_n = output_V_data_V_1_state[1'd1];
    end else begin
        m_axis_rx_data_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((output_V_data_V_1_sel == 1'b1)) begin
        output_V_data_V_1_data_out = output_V_data_V_1_payload_B;
    end else begin
        output_V_data_V_1_data_out = output_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_85 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_V_data_V_1_vld_in = 1'b1;
    end else begin
        output_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((output_V_keep_V_1_sel == 1'b1)) begin
        output_V_keep_V_1_data_out = output_V_keep_V_1_payload_B;
    end else begin
        output_V_keep_V_1_data_out = output_V_keep_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_85 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_V_keep_V_1_vld_in = 1'b1;
    end else begin
        output_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((output_V_last_V_1_sel == 1'b1)) begin
        output_V_last_V_1_data_out = output_V_last_V_1_payload_B;
    end else begin
        output_V_last_V_1_data_out = output_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((tmp_reg_85 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_V_last_V_1_vld_in = 1'b1;
    end else begin
        output_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_38_p5 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_udp2shiftFifo_V_d_blk_n = rx_udp2shiftFifo_V_d_empty_n;
    end else begin
        rx_udp2shiftFifo_V_d_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_38_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_udp2shiftFifo_V_d_read = 1'b1;
    end else begin
        rx_udp2shiftFifo_V_d_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_38_p5 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_udp2shiftFifo_V_k_blk_n = rx_udp2shiftFifo_V_k_empty_n;
    end else begin
        rx_udp2shiftFifo_V_k_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_38_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_udp2shiftFifo_V_k_read = 1'b1;
    end else begin
        rx_udp2shiftFifo_V_k_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_38_p5 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rx_udp2shiftFifo_V_l_blk_n = rx_udp2shiftFifo_V_l_empty_n;
    end else begin
        rx_udp2shiftFifo_V_l_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_38_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_udp2shiftFifo_V_l_read = 1'b1;
    end else begin
        rx_udp2shiftFifo_V_l_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_38_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((output_V_last_V_1_state == 2'd1) | (output_V_keep_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | ((output_V_last_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_38_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((output_V_last_V_1_state == 2'd1) | (output_V_keep_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state3_io) | ((output_V_last_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_38_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((output_V_last_V_1_state == 2'd1) | (output_V_keep_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | (1'b1 == ap_block_state3_io) | ((output_V_last_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_38_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = ((tmp_reg_85 == 1'd1) & (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((tmp_reg_85_pp0_iter1_reg == 1'd1) & (output_V_data_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((output_V_last_V_1_state == 2'd1) | (output_V_keep_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | ((output_V_last_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (m_axis_rx_data_TREADY == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign io_acc_block_signal_op6 = (rx_udp2shiftFifo_V_l_empty_n & rx_udp2shiftFifo_V_k_empty_n & rx_udp2shiftFifo_V_d_empty_n);

assign m_axis_rx_data_TDATA = output_V_data_V_1_data_out;

assign m_axis_rx_data_TKEEP = output_V_keep_V_1_data_out;

assign m_axis_rx_data_TLAST = output_V_last_V_1_data_out;

assign m_axis_rx_data_TVALID = output_V_last_V_1_state[1'd0];

assign output_V_data_V_1_ack_in = output_V_data_V_1_state[1'd1];

assign output_V_data_V_1_ack_out = m_axis_rx_data_TREADY;

assign output_V_data_V_1_load_A = (output_V_data_V_1_state_cmp_full & ~output_V_data_V_1_sel_wr);

assign output_V_data_V_1_load_B = (output_V_data_V_1_state_cmp_full & output_V_data_V_1_sel_wr);

assign output_V_data_V_1_sel = output_V_data_V_1_sel_rd;

assign output_V_data_V_1_state_cmp_full = ((output_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_data_V_1_vld_out = output_V_data_V_1_state[1'd0];

assign output_V_keep_V_1_ack_in = output_V_keep_V_1_state[1'd1];

assign output_V_keep_V_1_ack_out = m_axis_rx_data_TREADY;

assign output_V_keep_V_1_load_A = (output_V_keep_V_1_state_cmp_full & ~output_V_keep_V_1_sel_wr);

assign output_V_keep_V_1_load_B = (output_V_keep_V_1_state_cmp_full & output_V_keep_V_1_sel_wr);

assign output_V_keep_V_1_sel = output_V_keep_V_1_sel_rd;

assign output_V_keep_V_1_state_cmp_full = ((output_V_keep_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_keep_V_1_vld_out = output_V_keep_V_1_state[1'd0];

assign output_V_last_V_1_ack_in = output_V_last_V_1_state[1'd1];

assign output_V_last_V_1_ack_out = m_axis_rx_data_TREADY;

assign output_V_last_V_1_load_A = (output_V_last_V_1_state_cmp_full & ~output_V_last_V_1_sel_wr);

assign output_V_last_V_1_load_B = (output_V_last_V_1_state_cmp_full & output_V_last_V_1_sel_wr);

assign output_V_last_V_1_sel = output_V_last_V_1_sel_rd;

assign output_V_last_V_1_state_cmp_full = ((output_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_last_V_1_vld_out = output_V_last_V_1_state[1'd0];

assign tmp_nbreadreq_fu_38_p5 = (rx_udp2shiftFifo_V_l_empty_n & rx_udp2shiftFifo_V_k_empty_n & rx_udp2shiftFifo_V_d_empty_n);

endmodule //rshiftWordByOctet
