// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module check_icmp_checksum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_TVALID,
        packageBuffer1_V_din,
        packageBuffer1_V_full_n,
        packageBuffer1_V_write,
        validFifo_V_din,
        validFifo_V_full_n,
        validFifo_V_write,
        checksumStreams_V_V_s_din,
        checksumStreams_V_V_s_full_n,
        checksumStreams_V_V_s_write,
        s_axis_TDATA,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   s_axis_TVALID;
output  [72:0] packageBuffer1_V_din;
input   packageBuffer1_V_full_n;
output   packageBuffer1_V_write;
output  [0:0] validFifo_V_din;
input   validFifo_V_full_n;
output   validFifo_V_write;
output  [15:0] checksumStreams_V_V_s_din;
input   checksumStreams_V_V_s_full_n;
output   checksumStreams_V_V_s_write;
input  [63:0] s_axis_TDATA;
output   s_axis_TREADY;
input  [7:0] s_axis_TKEEP;
input  [0:0] s_axis_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[72:0] packageBuffer1_V_din;
reg packageBuffer1_V_write;
reg[0:0] validFifo_V_din;
reg validFifo_V_write;
reg checksumStreams_V_V_s_write;
reg s_axis_TREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] cics_writeLastOne_lo_load_fu_286_p1;
wire   [0:0] cics_computeCs_load_load_fu_290_p1;
wire   [0:0] tmp_nbreadreq_fu_162_p5;
reg    ap_predicate_op18_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] cics_writeLastOne_lo_reg_1400;
reg   [0:0] cics_computeCs_load_reg_1404;
reg   [0:0] tmp_reg_1408;
reg   [15:0] t_V_1_reg_1436;
reg    ap_predicate_op212_write_state2;
reg    ap_predicate_op218_write_state2;
reg    ap_predicate_op228_write_state2;
reg   [1:0] t_V_reg_1468;
reg   [0:0] and_ln91_1_reg_1472;
reg    ap_predicate_op235_write_state2;
reg    ap_predicate_op237_write_state2;
reg    ap_predicate_op239_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] cics_writeLastOne;
reg   [63:0] cics_prevWord_data_V;
reg   [7:0] cics_prevWord_keep_V;
reg   [0:0] cics_prevWord_last_V;
reg   [0:0] cics_computeCs;
reg   [15:0] cics_sums_V_2;
reg   [16:0] cics_sums_V_0;
reg   [15:0] cics_sums_V_3;
reg   [15:0] cics_sums_V_1;
reg   [16:0] icmpChecksum_V;
reg   [7:0] icmpType_V;
reg   [7:0] icmpCode_V;
reg   [1:0] cics_state_V;
reg   [15:0] cics_wordCount_V;
reg    s_axis_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    packageBuffer1_V_blk_n;
reg    validFifo_V_blk_n;
reg    checksumStreams_V_V_s_blk_n;
reg   [63:0] tmp_data_V_26_reg_1412;
reg   [7:0] tmp_keep_V_20_reg_1422;
wire   [0:0] tmp_last_V_17_fu_343_p1;
reg   [0:0] tmp_last_V_17_reg_1427;
wire   [0:0] trunc_ln321_fu_347_p1;
wire   [15:0] t_V_1_load_fu_351_p1;
wire   [0:0] icmp_ln879_3_fu_491_p2;
wire   [0:0] icmp_ln879_4_fu_637_p2;
wire   [0:0] tmp_33_fu_643_p3;
wire   [0:0] icmp_ln879_5_fu_767_p2;
wire   [0:0] tmp_36_fu_773_p3;
wire   [0:0] icmp_ln879_6_fu_887_p2;
wire   [0:0] tmp_39_fu_893_p3;
wire   [1:0] t_V_load_fu_1022_p1;
wire   [0:0] and_ln91_1_fu_1054_p2;
reg    ap_block_pp0_stage0_subdone;
reg   [15:0] ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207;
wire   [15:0] add_ln700_14_fu_997_p2;
reg   [63:0] ap_phi_mux_empty_52_phi_fu_220_p8;
wire   [63:0] p_Result_10_fu_1296_p5;
reg   [63:0] ap_phi_reg_pp0_iter1_empty_52_reg_217;
wire   [63:0] ap_phi_reg_pp0_iter0_empty_52_reg_217;
wire   [15:0] add_ln214_9_fu_403_p2;
wire   [15:0] add_ln214_23_fu_817_p2;
wire   [15:0] add_ln214_21_fu_865_p2;
wire   [16:0] zext_ln214_6_fu_547_p1;
wire   [16:0] zext_ln214_5_fu_617_p1;
wire   [16:0] r_V_3_fu_1066_p2;
wire   [16:0] zext_ln214_3_fu_1112_p1;
wire   [16:0] zext_ln214_fu_1156_p1;
wire   [15:0] add_ln214_11_fu_451_p2;
wire   [15:0] add_ln214_27_fu_937_p2;
wire   [15:0] add_ln214_25_fu_985_p2;
wire   [15:0] add_ln214_19_fu_687_p2;
wire   [15:0] add_ln214_17_fu_745_p2;
wire   [15:0] add_ln214_5_fu_1190_p2;
wire   [16:0] p_Result_s_fu_1253_p3;
wire   [16:0] grp_fu_275_p2;
wire   [16:0] zext_ln214_4_fu_1379_p1;
wire   [7:0] grp_fu_230_p4;
wire   [7:0] grp_fu_239_p4;
wire   [1:0] add_ln700_6_fu_1202_p2;
wire   [72:0] tmp_2_fu_1267_p4;
reg    ap_block_pp0_stage0_01001;
wire   [72:0] tmp_1_fu_1308_p4;
wire   [72:0] tmp_3_fu_1319_p4;
wire   [72:0] tmp12_fu_1389_p4;
wire   [15:0] p_Result_123_i_fu_367_p3;
wire   [16:0] zext_ln700_fu_298_p1;
wire   [16:0] zext_ln700_3_fu_375_p1;
wire   [16:0] add_ln700_3_fu_379_p2;
wire   [0:0] tmp_28_fu_385_p3;
wire   [15:0] zext_ln214_10_fu_393_p1;
wire   [15:0] add_ln214_8_fu_397_p2;
wire   [7:0] grp_fu_257_p4;
wire   [7:0] grp_fu_248_p4;
wire   [15:0] p_Result_123_1_i_fu_415_p3;
wire   [16:0] zext_ln700_1_fu_310_p1;
wire   [16:0] zext_ln700_4_fu_423_p1;
wire   [16:0] add_ln700_4_fu_427_p2;
wire   [0:0] tmp_29_fu_433_p3;
wire   [15:0] zext_ln214_11_fu_441_p1;
wire   [15:0] add_ln214_10_fu_445_p2;
wire   [1:0] trunc_ln647_5_fu_487_p1;
wire   [7:0] trunc_ln647_9_fu_497_p1;
wire   [15:0] p_Result_134_i_fu_501_p3;
wire   [16:0] zext_ln700_6_fu_509_p1;
wire   [16:0] add_ln700_7_fu_517_p2;
wire   [0:0] tmp_31_fu_523_p3;
wire   [15:0] zext_ln214_13_fu_531_p1;
wire   [15:0] trunc_ln700_3_fu_513_p1;
wire   [15:0] add_ln214_14_fu_535_p2;
wire   [15:0] add_ln214_15_fu_541_p2;
wire   [7:0] trunc_ln647_8_fu_567_p1;
wire   [7:0] p_Result_128_i_fu_557_p4;
wire   [15:0] p_Result_131_i_fu_571_p3;
wire   [16:0] zext_ln700_5_fu_579_p1;
wire   [16:0] add_ln700_5_fu_587_p2;
wire   [0:0] tmp_30_fu_593_p3;
wire   [15:0] zext_ln214_12_fu_601_p1;
wire   [15:0] trunc_ln700_2_fu_583_p1;
wire   [15:0] add_ln214_12_fu_605_p2;
wire   [15:0] add_ln214_13_fu_611_p2;
wire   [1:0] p_Result_127_1_i_fu_627_p4;
wire   [7:0] grp_fu_266_p4;
wire   [15:0] p_Result_134_1_i_fu_651_p3;
wire   [16:0] zext_ln700_8_fu_659_p1;
wire   [16:0] zext_ln700_2_fu_318_p1;
wire   [16:0] add_ln700_9_fu_663_p2;
wire   [0:0] tmp_34_fu_669_p3;
wire   [15:0] zext_ln214_15_fu_677_p1;
wire   [15:0] add_ln214_18_fu_681_p2;
wire   [7:0] p_Result_128_1_i_fu_699_p4;
wire   [15:0] p_Result_131_1_i_fu_709_p3;
wire   [16:0] zext_ln700_7_fu_717_p1;
wire   [16:0] add_ln700_8_fu_721_p2;
wire   [0:0] tmp_32_fu_727_p3;
wire   [15:0] zext_ln214_14_fu_735_p1;
wire   [15:0] add_ln214_16_fu_739_p2;
wire   [1:0] p_Result_127_2_i_fu_757_p4;
wire   [15:0] p_Result_134_2_i_fu_781_p3;
wire   [16:0] zext_ln700_10_fu_789_p1;
wire   [16:0] add_ln700_11_fu_793_p2;
wire   [0:0] tmp_37_fu_799_p3;
wire   [15:0] zext_ln214_17_fu_807_p1;
wire   [15:0] add_ln214_22_fu_811_p2;
wire   [15:0] p_Result_131_2_i_fu_829_p3;
wire   [16:0] zext_ln700_9_fu_837_p1;
wire   [16:0] add_ln700_10_fu_841_p2;
wire   [0:0] tmp_35_fu_847_p3;
wire   [15:0] zext_ln214_16_fu_855_p1;
wire   [15:0] add_ln214_20_fu_859_p2;
wire   [1:0] p_Result_127_3_i_fu_877_p4;
wire   [15:0] p_Result_134_3_i_fu_901_p3;
wire   [16:0] zext_ln700_12_fu_909_p1;
wire   [16:0] add_ln700_13_fu_913_p2;
wire   [0:0] tmp_40_fu_919_p3;
wire   [15:0] zext_ln214_19_fu_927_p1;
wire   [15:0] add_ln214_26_fu_931_p2;
wire   [15:0] p_Result_131_3_i_fu_949_p3;
wire   [16:0] zext_ln700_11_fu_957_p1;
wire   [16:0] add_ln700_12_fu_961_p2;
wire   [0:0] tmp_38_fu_967_p3;
wire   [15:0] zext_ln214_18_fu_975_p1;
wire   [15:0] add_ln214_24_fu_979_p2;
wire   [15:0] trunc_ln647_fu_1026_p1;
wire   [0:0] icmp_ln879_1_fu_1036_p2;
wire   [0:0] icmp_ln879_2_fu_1042_p2;
wire   [0:0] and_ln91_fu_1048_p2;
wire   [0:0] icmp_ln879_fu_1030_p2;
wire   [16:0] add_ln700_2_fu_1082_p2;
wire   [0:0] tmp_26_fu_1088_p3;
wire   [15:0] zext_ln214_9_fu_1096_p1;
wire   [15:0] trunc_ln700_1_fu_1078_p1;
wire   [15:0] add_ln214_6_fu_1100_p2;
wire   [15:0] add_ln214_7_fu_1106_p2;
wire   [16:0] add_ln700_fu_1126_p2;
wire   [0:0] tmp_24_fu_1132_p3;
wire   [15:0] zext_ln214_7_fu_1140_p1;
wire   [15:0] trunc_ln700_fu_1122_p1;
wire   [15:0] add_ln214_fu_1144_p2;
wire   [15:0] add_ln214_3_fu_1150_p2;
wire   [16:0] add_ln700_1_fu_1166_p2;
wire   [0:0] tmp_25_fu_1172_p3;
wire   [15:0] zext_ln214_8_fu_1180_p1;
wire   [15:0] add_ln214_4_fu_1184_p2;
wire   [15:0] p_Result_27_i_fu_1244_p4;
wire   [31:0] trunc_ln647_7_fu_1241_p1;
wire   [31:0] trunc_ln647_6_fu_1237_p1;
wire   [31:0] p_Result_29_i_fu_1278_p4;
wire   [39:0] tmp_23_i_fu_1288_p3;
wire   [16:0] add_ln701_fu_1351_p2;
wire   [0:0] tmp_27_fu_1357_p3;
wire   [15:0] trunc_ln214_fu_1365_p1;
wire   [15:0] zext_ln214_20_fu_1369_p1;
wire   [15:0] sub_ln214_fu_1373_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_373;
reg    ap_condition_1011;
reg    ap_condition_1009;
reg    ap_condition_1017;
reg    ap_condition_1024;
reg    ap_condition_1027;
reg    ap_condition_1034;
reg    ap_condition_1037;
reg    ap_condition_1043;
reg    ap_condition_1046;
reg    ap_condition_371;
reg    ap_condition_1052;
reg    ap_condition_1055;
reg    ap_condition_249;
reg    ap_condition_137;
reg    ap_condition_384;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 cics_writeLastOne = 1'd0;
#0 cics_prevWord_data_V = 64'd0;
#0 cics_prevWord_keep_V = 8'd0;
#0 cics_prevWord_last_V = 1'd0;
#0 cics_computeCs = 1'd0;
#0 cics_sums_V_2 = 16'd0;
#0 cics_sums_V_0 = 17'd0;
#0 cics_sums_V_3 = 16'd0;
#0 cics_sums_V_1 = 16'd0;
#0 icmpChecksum_V = 17'd0;
#0 icmpType_V = 8'd0;
#0 icmpCode_V = 8'd0;
#0 cics_state_V = 2'd0;
#0 cics_wordCount_V = 16'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((t_V_1_load_fu_351_p1 == 16'd1) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((t_V_1_load_fu_351_p1 == 16'd0) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter1_empty_52_reg_217 <= s_axis_TDATA;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_empty_52_reg_217 <= ap_phi_reg_pp0_iter0_empty_52_reg_217;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1009)) begin
        if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (t_V_load_fu_1022_p1 == 2'd3))) begin
            cics_computeCs <= 1'd0;
        end else if ((1'b1 == ap_condition_1011)) begin
            cics_computeCs <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1009)) begin
        if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (t_V_load_fu_1022_p1 == 2'd0))) begin
            cics_sums_V_0 <= zext_ln214_fu_1156_p1;
        end else if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (t_V_load_fu_1022_p1 == 2'd1))) begin
            cics_sums_V_0 <= zext_ln214_3_fu_1112_p1;
        end else if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (t_V_load_fu_1022_p1 == 2'd2))) begin
            cics_sums_V_0 <= r_V_3_fu_1066_p2;
        end else if ((1'b1 == ap_condition_1027)) begin
            cics_sums_V_0 <= zext_ln214_5_fu_617_p1;
        end else if ((1'b1 == ap_condition_1024)) begin
            cics_sums_V_0 <= zext_ln214_6_fu_547_p1;
        end else if ((1'b1 == ap_condition_1017)) begin
            cics_sums_V_0 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1009)) begin
        if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (t_V_load_fu_1022_p1 == 2'd0))) begin
            cics_sums_V_1 <= add_ln214_5_fu_1190_p2;
        end else if ((1'b1 == ap_condition_1037)) begin
            cics_sums_V_1 <= add_ln214_17_fu_745_p2;
        end else if ((1'b1 == ap_condition_1034)) begin
            cics_sums_V_1 <= add_ln214_19_fu_687_p2;
        end else if ((1'b1 == ap_condition_1017)) begin
            cics_sums_V_1 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_371)) begin
        if ((1'b1 == ap_condition_1046)) begin
            cics_sums_V_2 <= add_ln214_21_fu_865_p2;
        end else if ((1'b1 == ap_condition_1043)) begin
            cics_sums_V_2 <= add_ln214_23_fu_817_p2;
        end else if ((t_V_1_load_fu_351_p1 == 16'd0)) begin
            cics_sums_V_2 <= 16'd0;
        end else if ((t_V_1_load_fu_351_p1 == 16'd2)) begin
            cics_sums_V_2 <= add_ln214_9_fu_403_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_371)) begin
        if ((1'b1 == ap_condition_1055)) begin
            cics_sums_V_3 <= add_ln214_25_fu_985_p2;
        end else if ((1'b1 == ap_condition_1052)) begin
            cics_sums_V_3 <= add_ln214_27_fu_937_p2;
        end else if ((t_V_1_load_fu_351_p1 == 16'd0)) begin
            cics_sums_V_3 <= 16'd0;
        end else if ((t_V_1_load_fu_351_p1 == 16'd2)) begin
            cics_sums_V_3 <= add_ln214_11_fu_451_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_137)) begin
        if ((cics_writeLastOne_lo_load_fu_286_p1 == 1'd1)) begin
            cics_writeLastOne <= 1'd0;
        end else if ((1'b1 == ap_condition_249)) begin
            cics_writeLastOne <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((t_V_reg_1468 == 2'd1) & (cics_computeCs_load_reg_1404 == 1'd1) & (cics_writeLastOne_lo_reg_1400 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmpChecksum_V <= zext_ln214_4_fu_1379_p1;
    end else if ((((t_V_reg_1468 == 2'd0) & (cics_computeCs_load_reg_1404 == 1'd1) & (cics_writeLastOne_lo_reg_1400 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((t_V_reg_1468 == 2'd2) & (cics_computeCs_load_reg_1404 == 1'd1) & (cics_writeLastOne_lo_reg_1400 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        icmpChecksum_V <= grp_fu_275_p2;
    end else if (((t_V_1_reg_1436 == 16'd2) & (tmp_reg_1408 == 1'd1) & (cics_computeCs_load_reg_1404 == 1'd0) & (cics_writeLastOne_lo_reg_1400 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmpChecksum_V <= p_Result_s_fu_1253_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (cics_writeLastOne == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (t_V_load_fu_1022_p1 == 2'd3))) begin
        and_ln91_1_reg_1472 <= and_ln91_1_fu_1054_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((cics_writeLastOne == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cics_computeCs_load_reg_1404 <= cics_computeCs;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_1408 == 1'd1) & (cics_computeCs_load_reg_1404 == 1'd0) & (cics_writeLastOne_lo_reg_1400 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cics_prevWord_data_V <= ap_phi_mux_empty_52_phi_fu_220_p8;
        cics_prevWord_keep_V <= tmp_keep_V_20_reg_1422;
        cics_prevWord_last_V <= tmp_last_V_17_reg_1427;
    end
end

always @ (posedge ap_clk) begin
    if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cics_state_V <= add_ln700_6_fu_1202_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cics_wordCount_V <= ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cics_writeLastOne_lo_reg_1400 <= cics_writeLastOne;
    end
end

always @ (posedge ap_clk) begin
    if (((t_V_1_load_fu_351_p1 == 16'd2) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmpCode_V <= {{s_axis_TDATA[47:40]}};
        icmpType_V <= {{s_axis_TDATA[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_1_reg_1436 <= cics_wordCount_V;
        tmp_data_V_26_reg_1412 <= s_axis_TDATA;
        tmp_keep_V_20_reg_1422 <= s_axis_TKEEP;
        tmp_last_V_17_reg_1427 <= s_axis_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((cics_computeCs_load_load_fu_290_p1 == 1'd1) & (cics_writeLastOne == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_reg_1468 <= cics_state_V;
    end
end

always @ (posedge ap_clk) begin
    if (((cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_1408 <= tmp_nbreadreq_fu_162_p5;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_373)) begin
        if ((tmp_last_V_17_fu_343_p1 == 1'd0)) begin
            ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 = add_ln700_14_fu_997_p2;
        end else if ((tmp_last_V_17_fu_343_p1 == 1'd1)) begin
            ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 = 16'd0;
        end else begin
            ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 = ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207;
        end
    end else begin
        ap_phi_mux_cics_wordCount_V_new_phi_fu_210_p4 = ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207;
    end
end

always @ (*) begin
    if (((t_V_1_reg_1436 == 16'd2) & (tmp_reg_1408 == 1'd1) & (cics_computeCs_load_reg_1404 == 1'd0) & (cics_writeLastOne_lo_reg_1400 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_empty_52_phi_fu_220_p8 = p_Result_10_fu_1296_p5;
    end else begin
        ap_phi_mux_empty_52_phi_fu_220_p8 = ap_phi_reg_pp0_iter1_empty_52_reg_217;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op239_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        checksumStreams_V_V_s_blk_n = checksumStreams_V_V_s_full_n;
    end else begin
        checksumStreams_V_V_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op239_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        checksumStreams_V_V_s_write = 1'b1;
    end else begin
        checksumStreams_V_V_s_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op228_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op218_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op212_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((cics_writeLastOne_lo_reg_1400 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        packageBuffer1_V_blk_n = packageBuffer1_V_full_n;
    end else begin
        packageBuffer1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_384)) begin
        if ((cics_writeLastOne_lo_reg_1400 == 1'd1)) begin
            packageBuffer1_V_din = tmp12_fu_1389_p4;
        end else if ((ap_predicate_op228_write_state2 == 1'b1)) begin
            packageBuffer1_V_din = tmp_3_fu_1319_p4;
        end else if ((ap_predicate_op218_write_state2 == 1'b1)) begin
            packageBuffer1_V_din = tmp_1_fu_1308_p4;
        end else if ((ap_predicate_op212_write_state2 == 1'b1)) begin
            packageBuffer1_V_din = tmp_2_fu_1267_p4;
        end else begin
            packageBuffer1_V_din = 'bx;
        end
    end else begin
        packageBuffer1_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op228_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op218_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op212_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((cics_writeLastOne_lo_reg_1400 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        packageBuffer1_V_write = 1'b1;
    end else begin
        packageBuffer1_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op18_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op18_read_state1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        s_axis_TREADY = 1'b1;
    end else begin
        s_axis_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op237_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op235_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)))) begin
        validFifo_V_blk_n = validFifo_V_full_n;
    end else begin
        validFifo_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_384)) begin
        if ((ap_predicate_op237_write_state2 == 1'b1)) begin
            validFifo_V_din = 1'd1;
        end else if ((ap_predicate_op235_write_state2 == 1'b1)) begin
            validFifo_V_din = 1'd0;
        end else begin
            validFifo_V_din = 'bx;
        end
    end else begin
        validFifo_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op237_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op235_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        validFifo_V_write = 1'b1;
    end else begin
        validFifo_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln214_10_fu_445_p2 = (zext_ln214_11_fu_441_p1 + p_Result_123_1_i_fu_415_p3);

assign add_ln214_11_fu_451_p2 = (cics_sums_V_3 + add_ln214_10_fu_445_p2);

assign add_ln214_12_fu_605_p2 = (zext_ln214_12_fu_601_p1 + p_Result_131_i_fu_571_p3);

assign add_ln214_13_fu_611_p2 = (trunc_ln700_2_fu_583_p1 + add_ln214_12_fu_605_p2);

assign add_ln214_14_fu_535_p2 = (zext_ln214_13_fu_531_p1 + p_Result_134_i_fu_501_p3);

assign add_ln214_15_fu_541_p2 = (trunc_ln700_3_fu_513_p1 + add_ln214_14_fu_535_p2);

assign add_ln214_16_fu_739_p2 = (p_Result_131_1_i_fu_709_p3 + zext_ln214_14_fu_735_p1);

assign add_ln214_17_fu_745_p2 = (add_ln214_16_fu_739_p2 + cics_sums_V_1);

assign add_ln214_18_fu_681_p2 = (p_Result_134_1_i_fu_651_p3 + zext_ln214_15_fu_677_p1);

assign add_ln214_19_fu_687_p2 = (add_ln214_18_fu_681_p2 + cics_sums_V_1);

assign add_ln214_20_fu_859_p2 = (p_Result_131_2_i_fu_829_p3 + zext_ln214_16_fu_855_p1);

assign add_ln214_21_fu_865_p2 = (add_ln214_20_fu_859_p2 + cics_sums_V_2);

assign add_ln214_22_fu_811_p2 = (p_Result_134_2_i_fu_781_p3 + zext_ln214_17_fu_807_p1);

assign add_ln214_23_fu_817_p2 = (add_ln214_22_fu_811_p2 + cics_sums_V_2);

assign add_ln214_24_fu_979_p2 = (p_Result_131_3_i_fu_949_p3 + zext_ln214_18_fu_975_p1);

assign add_ln214_25_fu_985_p2 = (add_ln214_24_fu_979_p2 + cics_sums_V_3);

assign add_ln214_26_fu_931_p2 = (p_Result_134_3_i_fu_901_p3 + zext_ln214_19_fu_927_p1);

assign add_ln214_27_fu_937_p2 = (add_ln214_26_fu_931_p2 + cics_sums_V_3);

assign add_ln214_3_fu_1150_p2 = (cics_sums_V_2 + add_ln214_fu_1144_p2);

assign add_ln214_4_fu_1184_p2 = (zext_ln214_8_fu_1180_p1 + cics_sums_V_3);

assign add_ln214_5_fu_1190_p2 = (cics_sums_V_1 + add_ln214_4_fu_1184_p2);

assign add_ln214_6_fu_1100_p2 = (zext_ln214_9_fu_1096_p1 + trunc_ln700_1_fu_1078_p1);

assign add_ln214_7_fu_1106_p2 = (cics_sums_V_1 + add_ln214_6_fu_1100_p2);

assign add_ln214_8_fu_397_p2 = (zext_ln214_10_fu_393_p1 + p_Result_123_i_fu_367_p3);

assign add_ln214_9_fu_403_p2 = (cics_sums_V_2 + add_ln214_8_fu_397_p2);

assign add_ln214_fu_1144_p2 = (zext_ln214_7_fu_1140_p1 + trunc_ln700_fu_1122_p1);

assign add_ln700_10_fu_841_p2 = (zext_ln700_9_fu_837_p1 + zext_ln700_fu_298_p1);

assign add_ln700_11_fu_793_p2 = (zext_ln700_10_fu_789_p1 + zext_ln700_fu_298_p1);

assign add_ln700_12_fu_961_p2 = (zext_ln700_11_fu_957_p1 + zext_ln700_1_fu_310_p1);

assign add_ln700_13_fu_913_p2 = (zext_ln700_12_fu_909_p1 + zext_ln700_1_fu_310_p1);

assign add_ln700_14_fu_997_p2 = (cics_wordCount_V + 16'd1);

assign add_ln700_1_fu_1166_p2 = (zext_ln700_2_fu_318_p1 + zext_ln700_1_fu_310_p1);

assign add_ln700_2_fu_1082_p2 = (zext_ln700_2_fu_318_p1 + cics_sums_V_0);

assign add_ln700_3_fu_379_p2 = (zext_ln700_fu_298_p1 + zext_ln700_3_fu_375_p1);

assign add_ln700_4_fu_427_p2 = (zext_ln700_1_fu_310_p1 + zext_ln700_4_fu_423_p1);

assign add_ln700_5_fu_587_p2 = (zext_ln700_5_fu_579_p1 + cics_sums_V_0);

assign add_ln700_6_fu_1202_p2 = (cics_state_V + 2'd1);

assign add_ln700_7_fu_517_p2 = (zext_ln700_6_fu_509_p1 + cics_sums_V_0);

assign add_ln700_8_fu_721_p2 = (zext_ln700_7_fu_717_p1 + zext_ln700_2_fu_318_p1);

assign add_ln700_9_fu_663_p2 = (zext_ln700_8_fu_659_p1 + zext_ln700_2_fu_318_p1);

assign add_ln700_fu_1126_p2 = (zext_ln700_fu_298_p1 + cics_sums_V_0);

assign add_ln701_fu_1351_p2 = ($signed(17'd131064) + $signed(icmpChecksum_V));

assign and_ln91_1_fu_1054_p2 = (icmp_ln879_fu_1030_p2 & and_ln91_fu_1048_p2);

assign and_ln91_fu_1048_p2 = (icmp_ln879_2_fu_1042_p2 & icmp_ln879_1_fu_1036_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((s_axis_TVALID == 1'b0) & (ap_predicate_op18_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((validFifo_V_full_n == 1'b0) & (ap_predicate_op237_write_state2 == 1'b1)) | ((validFifo_V_full_n == 1'b0) & (ap_predicate_op235_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op228_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op218_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op212_write_state2 == 1'b1)) | ((cics_writeLastOne_lo_reg_1400 == 1'd1) & (packageBuffer1_V_full_n == 1'b0)) | ((checksumStreams_V_V_s_full_n == 1'b0) & (ap_predicate_op239_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((s_axis_TVALID == 1'b0) & (ap_predicate_op18_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((validFifo_V_full_n == 1'b0) & (ap_predicate_op237_write_state2 == 1'b1)) | ((validFifo_V_full_n == 1'b0) & (ap_predicate_op235_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op228_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op218_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op212_write_state2 == 1'b1)) | ((cics_writeLastOne_lo_reg_1400 == 1'd1) & (packageBuffer1_V_full_n == 1'b0)) | ((checksumStreams_V_V_s_full_n == 1'b0) & (ap_predicate_op239_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((s_axis_TVALID == 1'b0) & (ap_predicate_op18_read_state1 == 1'b1)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((validFifo_V_full_n == 1'b0) & (ap_predicate_op237_write_state2 == 1'b1)) | ((validFifo_V_full_n == 1'b0) & (ap_predicate_op235_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op228_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op218_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op212_write_state2 == 1'b1)) | ((cics_writeLastOne_lo_reg_1400 == 1'd1) & (packageBuffer1_V_full_n == 1'b0)) | ((checksumStreams_V_V_s_full_n == 1'b0) & (ap_predicate_op239_write_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((s_axis_TVALID == 1'b0) & (ap_predicate_op18_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((validFifo_V_full_n == 1'b0) & (ap_predicate_op237_write_state2 == 1'b1)) | ((validFifo_V_full_n == 1'b0) & (ap_predicate_op235_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op228_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op218_write_state2 == 1'b1)) | ((packageBuffer1_V_full_n == 1'b0) & (ap_predicate_op212_write_state2 == 1'b1)) | ((cics_writeLastOne_lo_reg_1400 == 1'd1) & (packageBuffer1_V_full_n == 1'b0)) | ((checksumStreams_V_V_s_full_n == 1'b0) & (ap_predicate_op239_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_condition_1009 = ((cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_1011 = ((tmp_last_V_17_fu_343_p1 == 1'd1) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0));
end

always @ (*) begin
    ap_condition_1017 = ((t_V_1_load_fu_351_p1 == 16'd0) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0));
end

always @ (*) begin
    ap_condition_1024 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (trunc_ln321_fu_347_p1 == 1'd1) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (icmp_ln879_3_fu_491_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1027 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (icmp_ln879_3_fu_491_p2 == 1'd1) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0));
end

always @ (*) begin
    ap_condition_1034 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (tmp_33_fu_643_p3 == 1'd1) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (icmp_ln879_4_fu_637_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1037 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (icmp_ln879_4_fu_637_p2 == 1'd1) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0));
end

always @ (*) begin
    ap_condition_1043 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (tmp_36_fu_773_p3 == 1'd1) & (icmp_ln879_5_fu_767_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1046 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (icmp_ln879_5_fu_767_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_1052 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (tmp_39_fu_893_p3 == 1'd1) & (icmp_ln879_6_fu_887_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_1055 = (~(t_V_1_load_fu_351_p1 == 16'd2) & ~(t_V_1_load_fu_351_p1 == 16'd1) & ~(t_V_1_load_fu_351_p1 == 16'd0) & (icmp_ln879_6_fu_887_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_137 = ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_249 = ((tmp_last_V_17_fu_343_p1 == 1'd1) & (tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0));
end

always @ (*) begin
    ap_condition_371 = ((tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_373 = ((tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_384 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_cics_wordCount_V_new_reg_207 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_52_reg_217 = 'bx;

always @ (*) begin
    ap_predicate_op18_read_state1 = ((tmp_nbreadreq_fu_162_p5 == 1'd1) & (cics_computeCs == 1'd0) & (cics_writeLastOne == 1'd0));
end

always @ (*) begin
    ap_predicate_op212_write_state2 = ((t_V_1_reg_1436 == 16'd2) & (tmp_reg_1408 == 1'd1) & (cics_computeCs_load_reg_1404 == 1'd0) & (cics_writeLastOne_lo_reg_1400 == 1'd0));
end

always @ (*) begin
    ap_predicate_op218_write_state2 = ((t_V_1_reg_1436 == 16'd1) & (tmp_reg_1408 == 1'd1) & (cics_computeCs_load_reg_1404 == 1'd0) & (cics_writeLastOne_lo_reg_1400 == 1'd0));
end

always @ (*) begin
    ap_predicate_op228_write_state2 = (~(t_V_1_reg_1436 == 16'd0) & ~(t_V_1_reg_1436 == 16'd1) & ~(t_V_1_reg_1436 == 16'd2) & (tmp_reg_1408 == 1'd1) & (cics_computeCs_load_reg_1404 == 1'd0) & (cics_writeLastOne_lo_reg_1400 == 1'd0));
end

always @ (*) begin
    ap_predicate_op235_write_state2 = ((t_V_reg_1468 == 2'd3) & (cics_computeCs_load_reg_1404 == 1'd1) & (cics_writeLastOne_lo_reg_1400 == 1'd0) & (1'd0 == and_ln91_1_reg_1472));
end

always @ (*) begin
    ap_predicate_op237_write_state2 = ((t_V_reg_1468 == 2'd3) & (cics_computeCs_load_reg_1404 == 1'd1) & (1'd1 == and_ln91_1_reg_1472) & (cics_writeLastOne_lo_reg_1400 == 1'd0));
end

always @ (*) begin
    ap_predicate_op239_write_state2 = ((t_V_reg_1468 == 2'd3) & (cics_computeCs_load_reg_1404 == 1'd1) & (1'd1 == and_ln91_1_reg_1472) & (cics_writeLastOne_lo_reg_1400 == 1'd0));
end

assign checksumStreams_V_V_s_din = icmpChecksum_V[15:0];

assign cics_computeCs_load_load_fu_290_p1 = cics_computeCs;

assign cics_writeLastOne_lo_load_fu_286_p1 = cics_writeLastOne;

assign grp_fu_230_p4 = {{s_axis_TDATA[39:32]}};

assign grp_fu_239_p4 = {{s_axis_TDATA[47:40]}};

assign grp_fu_248_p4 = {{s_axis_TDATA[63:56]}};

assign grp_fu_257_p4 = {{s_axis_TDATA[55:48]}};

assign grp_fu_266_p4 = {{s_axis_TDATA[23:16]}};

assign grp_fu_275_p2 = (icmpChecksum_V ^ 17'd131071);

assign icmp_ln879_1_fu_1036_p2 = ((icmpType_V == 8'd8) ? 1'b1 : 1'b0);

assign icmp_ln879_2_fu_1042_p2 = ((icmpCode_V == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln879_3_fu_491_p2 = ((trunc_ln647_5_fu_487_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln879_4_fu_637_p2 = ((p_Result_127_1_i_fu_627_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln879_5_fu_767_p2 = ((p_Result_127_2_i_fu_757_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln879_6_fu_887_p2 = ((p_Result_127_3_i_fu_877_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_1030_p2 = ((trunc_ln647_fu_1026_p1 == 16'd0) ? 1'b1 : 1'b0);

assign p_Result_10_fu_1296_p5 = {{tmp_data_V_26_reg_1412[63:40]}, {tmp_23_i_fu_1288_p3}};

assign p_Result_123_1_i_fu_415_p3 = {{grp_fu_257_p4}, {grp_fu_248_p4}};

assign p_Result_123_i_fu_367_p3 = {{grp_fu_230_p4}, {grp_fu_239_p4}};

assign p_Result_127_1_i_fu_627_p4 = {{s_axis_TKEEP[3:2]}};

assign p_Result_127_2_i_fu_757_p4 = {{s_axis_TKEEP[5:4]}};

assign p_Result_127_3_i_fu_877_p4 = {{s_axis_TKEEP[7:6]}};

assign p_Result_128_1_i_fu_699_p4 = {{s_axis_TDATA[31:24]}};

assign p_Result_128_i_fu_557_p4 = {{s_axis_TDATA[15:8]}};

assign p_Result_131_1_i_fu_709_p3 = {{grp_fu_266_p4}, {p_Result_128_1_i_fu_699_p4}};

assign p_Result_131_2_i_fu_829_p3 = {{grp_fu_230_p4}, {grp_fu_239_p4}};

assign p_Result_131_3_i_fu_949_p3 = {{grp_fu_257_p4}, {grp_fu_248_p4}};

assign p_Result_131_i_fu_571_p3 = {{trunc_ln647_8_fu_567_p1}, {p_Result_128_i_fu_557_p4}};

assign p_Result_134_1_i_fu_651_p3 = {{grp_fu_266_p4}, {8'd0}};

assign p_Result_134_2_i_fu_781_p3 = {{grp_fu_230_p4}, {8'd0}};

assign p_Result_134_3_i_fu_901_p3 = {{grp_fu_257_p4}, {8'd0}};

assign p_Result_134_i_fu_501_p3 = {{trunc_ln647_9_fu_497_p1}, {8'd0}};

assign p_Result_27_i_fu_1244_p4 = {{tmp_data_V_26_reg_1412[63:48]}};

assign p_Result_29_i_fu_1278_p4 = {{cics_prevWord_data_V[63:32]}};

assign p_Result_s_fu_1253_p3 = {{1'd1}, {p_Result_27_i_fu_1244_p4}};

assign r_V_3_fu_1066_p2 = (cics_sums_V_0 ^ 17'd131071);

assign sub_ln214_fu_1373_p2 = (trunc_ln214_fu_1365_p1 - zext_ln214_20_fu_1369_p1);

assign t_V_1_load_fu_351_p1 = cics_wordCount_V;

assign t_V_load_fu_1022_p1 = cics_state_V;

assign tmp12_fu_1389_p4 = {{{cics_prevWord_last_V}, {cics_prevWord_keep_V}}, {cics_prevWord_data_V}};

assign tmp_1_fu_1308_p4 = {{{cics_prevWord_last_V}, {cics_prevWord_keep_V}}, {cics_prevWord_data_V}};

assign tmp_23_i_fu_1288_p3 = {{8'd0}, {p_Result_29_i_fu_1278_p4}};

assign tmp_24_fu_1132_p3 = add_ln700_fu_1126_p2[32'd16];

assign tmp_25_fu_1172_p3 = add_ln700_1_fu_1166_p2[32'd16];

assign tmp_26_fu_1088_p3 = add_ln700_2_fu_1082_p2[32'd16];

assign tmp_27_fu_1357_p3 = add_ln701_fu_1351_p2[32'd16];

assign tmp_28_fu_385_p3 = add_ln700_3_fu_379_p2[32'd16];

assign tmp_29_fu_433_p3 = add_ln700_4_fu_427_p2[32'd16];

assign tmp_2_fu_1267_p4 = {{{{9'd255}, {trunc_ln647_7_fu_1241_p1}}}, {trunc_ln647_6_fu_1237_p1}};

assign tmp_30_fu_593_p3 = add_ln700_5_fu_587_p2[32'd16];

assign tmp_31_fu_523_p3 = add_ln700_7_fu_517_p2[32'd16];

assign tmp_32_fu_727_p3 = add_ln700_8_fu_721_p2[32'd16];

assign tmp_33_fu_643_p3 = s_axis_TKEEP[32'd2];

assign tmp_34_fu_669_p3 = add_ln700_9_fu_663_p2[32'd16];

assign tmp_35_fu_847_p3 = add_ln700_10_fu_841_p2[32'd16];

assign tmp_36_fu_773_p3 = s_axis_TKEEP[32'd4];

assign tmp_37_fu_799_p3 = add_ln700_11_fu_793_p2[32'd16];

assign tmp_38_fu_967_p3 = add_ln700_12_fu_961_p2[32'd16];

assign tmp_39_fu_893_p3 = s_axis_TKEEP[32'd6];

assign tmp_3_fu_1319_p4 = {{{cics_prevWord_last_V}, {cics_prevWord_keep_V}}, {cics_prevWord_data_V}};

assign tmp_40_fu_919_p3 = add_ln700_13_fu_913_p2[32'd16];

assign tmp_last_V_17_fu_343_p1 = s_axis_TLAST;

assign tmp_nbreadreq_fu_162_p5 = s_axis_TVALID;

assign trunc_ln214_fu_1365_p1 = add_ln701_fu_1351_p2[15:0];

assign trunc_ln321_fu_347_p1 = s_axis_TKEEP[0:0];

assign trunc_ln647_5_fu_487_p1 = s_axis_TKEEP[1:0];

assign trunc_ln647_6_fu_1237_p1 = cics_prevWord_data_V[31:0];

assign trunc_ln647_7_fu_1241_p1 = tmp_data_V_26_reg_1412[31:0];

assign trunc_ln647_8_fu_567_p1 = s_axis_TDATA[7:0];

assign trunc_ln647_9_fu_497_p1 = s_axis_TDATA[7:0];

assign trunc_ln647_fu_1026_p1 = cics_sums_V_0[15:0];

assign trunc_ln700_1_fu_1078_p1 = cics_sums_V_0[15:0];

assign trunc_ln700_2_fu_583_p1 = cics_sums_V_0[15:0];

assign trunc_ln700_3_fu_513_p1 = cics_sums_V_0[15:0];

assign trunc_ln700_fu_1122_p1 = cics_sums_V_0[15:0];

assign zext_ln214_10_fu_393_p1 = tmp_28_fu_385_p3;

assign zext_ln214_11_fu_441_p1 = tmp_29_fu_433_p3;

assign zext_ln214_12_fu_601_p1 = tmp_30_fu_593_p3;

assign zext_ln214_13_fu_531_p1 = tmp_31_fu_523_p3;

assign zext_ln214_14_fu_735_p1 = tmp_32_fu_727_p3;

assign zext_ln214_15_fu_677_p1 = tmp_34_fu_669_p3;

assign zext_ln214_16_fu_855_p1 = tmp_35_fu_847_p3;

assign zext_ln214_17_fu_807_p1 = tmp_37_fu_799_p3;

assign zext_ln214_18_fu_975_p1 = tmp_38_fu_967_p3;

assign zext_ln214_19_fu_927_p1 = tmp_40_fu_919_p3;

assign zext_ln214_20_fu_1369_p1 = tmp_27_fu_1357_p3;

assign zext_ln214_3_fu_1112_p1 = add_ln214_7_fu_1106_p2;

assign zext_ln214_4_fu_1379_p1 = sub_ln214_fu_1373_p2;

assign zext_ln214_5_fu_617_p1 = add_ln214_13_fu_611_p2;

assign zext_ln214_6_fu_547_p1 = add_ln214_15_fu_541_p2;

assign zext_ln214_7_fu_1140_p1 = tmp_24_fu_1132_p3;

assign zext_ln214_8_fu_1180_p1 = tmp_25_fu_1172_p3;

assign zext_ln214_9_fu_1096_p1 = tmp_26_fu_1088_p3;

assign zext_ln214_fu_1156_p1 = add_ln214_3_fu_1150_p2;

assign zext_ln700_10_fu_789_p1 = p_Result_134_2_i_fu_781_p3;

assign zext_ln700_11_fu_957_p1 = p_Result_131_3_i_fu_949_p3;

assign zext_ln700_12_fu_909_p1 = p_Result_134_3_i_fu_901_p3;

assign zext_ln700_1_fu_310_p1 = cics_sums_V_3;

assign zext_ln700_2_fu_318_p1 = cics_sums_V_1;

assign zext_ln700_3_fu_375_p1 = p_Result_123_i_fu_367_p3;

assign zext_ln700_4_fu_423_p1 = p_Result_123_1_i_fu_415_p3;

assign zext_ln700_5_fu_579_p1 = p_Result_131_i_fu_571_p3;

assign zext_ln700_6_fu_509_p1 = p_Result_134_i_fu_501_p3;

assign zext_ln700_7_fu_717_p1 = p_Result_131_1_i_fu_709_p3;

assign zext_ln700_8_fu_659_p1 = p_Result_134_1_i_fu_651_p3;

assign zext_ln700_9_fu_837_p1 = p_Result_131_2_i_fu_829_p3;

assign zext_ln700_fu_298_p1 = cics_sums_V_2;

endmodule //check_icmp_checksum
